### ISSUE TITLE
google play support libraries update..

### ISSUE THREAD

**Issue by patrickdrd** [microg/android_packages_apps_GmsCore#807] opened 2019-06-03 10:02 UTC
after the latest version (0.2.7),
I'm (still) getting updating google play support libraries,
I thought this was because our gms core version was older than the latest google play services,
now it should be the same, so why is this (still) happening?
I also think that it's happening more than before as well
do you know why and/or can you fix it?

**Comment by Vavun** [comment] 2019-06-03 10:51
It's not an microG issue.
And there is nothing that needs to be fixed

**Comment by patrickdrd** [comment] 2019-06-03 10:54
well, I've only noticed it in this device that has microg installed,
I've never seen it before

after all, google play support libraries = google play services = gms core, no?

**Comment by chris42** [comment] 2019-06-03 11:04
Microg can't prevent the question for update. As soon as the service framework gets a new version you will get the request. Only solution is to use a store in which you can put applications to an ignore list (e.g. Aurora store).

However, currently the issue is valid, as the official version and microg version should not differ. Hence, if there is an update request something seems to be wrong?
@patrickdrd Do you have any Beta release channel activated? To which version does it want to update?

**Comment by patrickdrd** [comment] 2019-06-03 11:12
I don't think so, I never opt in for betas,
I don't have the time or the mood to do the beta testing, I always ignore them,
as for the version that's something I'm wondering too myself,
I don't know, I tried to check the logcat but I guess I was just a bit late,
because I couldn't find it, 
I'll keep an eye on next time I see it,
it was happening before too, but happening this time which equal version is unjustifiable

**Comment by patrickdrd** [comment] 2019-06-03 11:20
is it possible that it's trying to update google play store?
we haven't received the latest play store yet (the material one) by @Nanolx ,
maybe that's the culprit?

**Comment by Nanolx** [comment] 2019-06-03 11:54
The last version by me is 15.1.23, while the latest official is 15.1.24. I may roll-out that minor today, though I doubt that's the culprint. The patched Play Store cuts off several update requests, but not all, since some are triggered on server side.

I personally, don't get any update triggers since I using the combo of Play Store 15.1.23 and microG with version 14.7.55 spoofed. So I guess the material design update or Play Services beta channel (as pointed out by @chris42) may be the reason.

**Comment by patrickdrd** [comment] 2019-06-04 08:51
classic google, another update today, 15.2.23 ..

**Comment by Nanolx** [comment] 2019-06-04 19:10
@ale5000-git could you please close this issue? Thanks.

@patrickdrd please move future issues regarding the custom Play Store over at: https://gitlab.com/Nanolx/microg-phonesky-iap-support

I'll roll-out a patched version 15.2.23 during the next hour.

**Comment by ale5000-git** [comment] 2019-06-04 19:28
Closed as the problem isn't in microG.

**Closed by ale5000-git** 2019-06-04 19:28 UTC
Labels: invalid / wontfix

**Comment by patrickdrd** [comment] 2019-06-07 09:27
> Oh, updating to 15.1.24 immediately got me the Material Design update

so google got back the material design and 
gave it again today with version 15.2.38,
waiting for your update

**Comment by patrickdrd** [comment] 2019-06-12 14:38
so material design rolled back again for the 2nd time!! google seems undecided!
