### ISSUE TITLE
Discord push notifications are broken

### ISSUE THREAD

**Issue by ahstro** [microg/android_packages_apps_GmsCore#540] opened 2018-05-02 20:51 UTC
Discord does not register for push notifications, even though the setting is enabled. Push notifications work for other apps, e.g. Slack. I've tried removing and reinstalling the app, because I heard apps need to be installed after microg/spoofing/something is set up and I couldn't remember if it was, but that didn't help.

**Comment by xeals** [comment] 2018-05-05 07:36
I've set up a new phone yesterday and I can't register Discord at all. I get a notification saying that Google Play Services need to be updated. May be related.

**Comment by nermolov** [comment] 2018-05-06 21:16
Can confirm this issue on my end as well.

**Comment by bmccoy11** [comment] 2018-05-18 21:36
Riot's push notifications don't appear to be working for me either.

**Comment by Phantop** [comment] 2018-05-18 21:42
Getting the same Play Services update, even with Cloud Messaging enabled and with FakeStore on MicroG Lineage.

**Comment by Phantop** [comment] 2018-05-21 00:09
I skipped back a bit and can confirm that 6.4.7 works. Newer versions may work, I skipped by 5 months

**Comment by nermolov** [comment] 2018-05-21 19:16
@Phantop I tried downgrading to 6.4.7 and it still would not register with microg

**Comment by pejakm** [comment] 2018-06-03 18:46
> Riot's push notifications don't appear to be working for me either.

I can confirm this, too.

**Comment by pejakm** [comment] 2018-06-03 20:29
I have updated to the 0.2.4-11**8** ([download link](https://transfer.sh/dF3Nd/MicroG_GMS_Core-v0.2.4-118.apk) here: https://forum.xda-developers.com/showpost.php?p=76709522&postcount=4710) but still some apps cannot register, like the tester app shown below, and simply crash afterwards.

![screenshot_2018-06-03-22-06-12](https://user-images.githubusercontent.com/913292/40890882-30d3a550-677d-11e8-8752-bb362b777590.png)

**Comment by pejakm** [comment] 2018-06-03 20:50
[log.txt](https://github.com/microg/android_packages_apps_GmsCore/files/2066339/log.txt)
[log2.txt](https://github.com/microg/android_packages_apps_GmsCore/files/2066340/log2.txt)

Okay, here are some logs, hope they will help.

**Comment by ahstro** [comment] 2018-06-04 08:01
Sorry for off-topic, but @pejakm, what is that tester app called?

**Comment by pejakm** [comment] 2018-06-04 08:56
@ahstro https://play.google.com/store/apps/details?id=com.firstrowria.pushnotificationtester

**Comment by chris42** [comment] 2018-06-04 09:58
My experience:
microg nly supports methods of registering push notifications for GCM.
Since October/November last year most Apps now use the new version called FCM. Apparently that does not work with microg and I do not know if there will be a fix.
Hence you might see very different results for each app, depending if it upgraded or not. Hence notification tester might work, but app not.
For some apps it helps to install an older version from last year first and then upgrade.

Also please note Push notification registration problems are different than the google framework version problems. Only if you get the explicit message for the google framework version you have an issue there.
With Discord it seems you have both problems, FCM and current version number of google framework is needed.

**Comment by DPTJKKVH** [comment] 2018-08-29 14:17
Please check if it works again with the most recent version: 12.8.79 found on f-droid.

https://github.com/microg/android_packages_apps_GmsCore/commit/4040e3df85db5dd59ed3028978a33eb92d7f4e46

**Comment by ale5000-git** [comment] 2018-08-29 17:55
The version of microG GmsCore is 0.2.5.12879

**Comment by frstrikerman** [comment] 2018-08-30 16:50
Push notification tester still crash and no apps seams to be able to register since I updated (I use lineages 1.5.1 for microg).

**Comment by ale5000-git** [comment] 2018-08-30 18:33
Have you verified manually that you have microG GmsCore **0.2.5.12879**?
Many times F-Droid make believe that it is update but it isn't (this apply specially to microG GmsCore).

**Comment by frstrikerman** [comment] 2018-08-30 18:53
@ale5000-git yes I did ![](https://i.imgur.com/n8fjpB8.png) ![](https://i.imgur.com/YQuxSBG.png)

**Comment by frstrikerman** [comment] 2018-08-30 21:58
@ale5000-git I just tried that and push notification tester still crash

**Comment by chris42** [comment] 2018-09-04 17:15
The patch out of #439 still has some issues. The registered apps will not show as registered in microg settings, however will work to deliver push messages. Only a few apps have troubles (so far known: Threema)
I tested the push notification tester on microg 0.2.5.12879 on AOSP and it worked.

**Comment by pejakm** [comment] 2018-09-04 17:36
> Only a few apps have troubles (so far known: Threema)

2. Signal can't register;
3. Viber works for few hours after fresh install or reinstall, then does not receive notifications.

**Comment by chris42** [comment] 2018-09-04 17:55
@pejakm 
Could you please send some logs, especially captured during registration. e.g. via catlog

Also please make sure the following was done before:
- you are using newest microg version 0.2.5-12879 running (ale5000 installer is updated and should be very helpful)
- you activated google device registration
- you get all the green checkmarks in microg diagnostics
- nothing is blocking network traffic to mtalk.google.com (e.g. afwall, adaway, ...)
- you deleted the app you have troubles with and installed it fresh after updating to microg 0.2.5-12879
- you have not used backup solutions, like oandbackup, titaniumbackup, ... to restore app data
- you used push notification tester to check. I just tried it and it works.

**Comment by pejakm** [comment] 2018-09-08 16:41
Ah, just tried with another number, and went through. So Signal works with microG.

**Comment by chris42** [comment] 2018-09-08 18:34
Good to hear. If you are still looking into viber, check the logs for the "GmsGcmMcsInput" messages. These should appear in the log when a message is received.

**Comment by godoftech** [comment] 2018-10-11 16:14
Possible workaround:
https://github.com/microg/android_packages_apps_GmsCore/issues/631#issuecomment-429013399

**Comment by Littner64** [comment] 2019-04-27 22:19
Version 5.7.9 solves the connection problem: [https://www.apkmirror.com/apk/discord-inc/discord-chat-for-gamers/discord-chat-for-gamers-5-7-9-release/](url)

**Comment by ale5000-git** [comment] 2019-06-02 14:08
The problem should be fixed in recent versions of microG GmsCore, I'm closing this for now.
Please try it and report back.

**Closed by ale5000-git** 2019-06-02 14:08 UTC
Labels: ☁️ Cloud / Push Messaging

**Comment by nathanfranke** [comment] 2023-08-13 01:17
This resolved my issue https://github.com/microg/GmsCore/issues/1573#issuecomment-1066064144

**Comment by wilawola** [comment] 2026-06-05 08:07
Discord push notifications also doesn't work for me too, not only that, google maps barely works, these two apps need to be dealt with accordingly.
