### ISSUE TITLE
Wire Doesn't Seem To Work With GCM

### ISSUE THREAD

**Issue by cwmke** [microg/android_packages_apps_GmsCore#115] opened 2016-04-12 05:49 UTC
Push messaging doesn't work for Wire 2.3.211 on android 6.0.1.  Thanks for any help and for the wonderful microg project.

```
04-12 00:37:46.625 D/GmsGcmMcsInput(6506): Incoming message: DataMessageStanza{id=F02FE302, from=782078216207, 
category=com.wire, token=do_not_collapse, app_data=[AppData{key=data, value=REMOVEDBYME}, 
AppData{key=type, value=cipher}, 
AppData{key=mac, value=REMOVEDBYME}], 
from_trusted_server=false, persistent_id=0:REMOVEDBYME, sent=REMOVEDBYME}

04-12 00:37:46.639 D/GmsGcmMcsSvc(6506): Target: ResolveInfo{71a4789 
com.wire/com.localytics.android.PushReceiver m=0x108000}

04-12 00:37:46.643 W/BroadcastQueue(4792): Permission Denial: receiving Intent { 
act=com.google.android.c2dm.intent.RECEIVE flg=0x30 pkg=com.wire 
cmp=com.wire/com.localytics.android.PushReceiver (has extras) } to 
com.wire/com.localytics.android.PushReceiver requires 
com.wire.permission.C2D_MESSAGE due to sender com.google.android.gms (uid 10089)

04-12 00:37:46.645 D/GmsGcmMcsSvc(6506): Target: ResolveInfo{4f2638e 
com.wire/com.waz.zms.GcmBroadcastReceiver m=0x108000}

04-12 00:37:46.647 W/BroadcastQueue(4792): Permission Denial: receiving Intent { 
act=com.google.android.c2dm.intent.RECEIVE flg=0x30 pkg=com.wire 
cmp=com.wire/com.waz.zms.GcmBroadcastReceiver (has extras) } to 
com.wire/com.waz.zms.GcmBroadcastReceiver requires 
com.wire.permission.C2D_MESSAGE due to sender com.google.android.gms (uid 10089)

```
##

**Comment by cwmke** [comment] 2016-07-22 16:59
They recently open sourced with GPL3.
App - [wireapp/wire-android](https://github.com/wireapp/wire-android)
Sync - [wireapp/zmessaging-android](https://github.com/wireapp/zmessaging-android)

**Comment by ale5000-git** [comment] 2016-11-27 14:44
Have you tried with the latest preview version of microG GmsCore (currently 0.2.4-**28**)?

**Comment by cwmke** [comment] 2016-11-27 16:03
I haven't. I switched to Copperhead which doesn't currently support signature spoofing so I have no way to test. Hopefully someone else can take a look and confirm.

**Comment by ale5000-git** [comment] 2016-11-27 18:48
If it is just for that, you can add support for signature spoofing in any ROM with [Tingle](https://github.com/ale5000-git/tingle).

**Comment by Salothin** [comment] 2017-02-23 12:22
The issue is fixed by Wire, this issue may be closed.

ref: https://github.com/wireapp/wire-android/issues/573

**Closed** 2017-02-23 14:31 UTC
