### ISSUE TITLE
Telegram does not register GCM

### ISSUE THREAD

**Issue by cRaZy-bisCuiT** [microg/android_packages_apps_GmsCore#605] opened 2018-09-03 20:33 UTC
Upstream/PlayStore Telegram does not register as a GCM app. What kind of logs do you need / how can I fix that?

**Comment by breversa** [comment] 2018-09-04 14:48
Gmail doesn't either. Maybe the cause is the same ?
MicroG 0.2.5.12879

**Comment by Vavun** [comment] 2018-09-04 16:07
It can be solved by installing old version of problem app.
After it you can upgrade problem app to up to date release

**Comment by chris42** [comment] 2018-09-04 16:58
Other people reported it to receive push messages. Please be aware, that it is shown in the microg settings as "not registered" although it is. This is a known bug.
You can right now only verify, if you check if messages appear on time.

**Comment by chris42** [comment] 2018-09-04 17:05
#439

**Comment by cRaZy-bisCuiT** [comment] 2018-09-06 10:27
@chris42 It is shown as not registered but messages arrive, yes. But why is Telegram draining the battery then? It's the app using the battery the most.

**Comment by chris42** [comment] 2018-09-06 10:47
@cRaZy-bisCuiT 
Is battery optimization deactivated for Telegram?

Otherwise this is rather a difficult question then. Normally you would see in microg if push messages were received, but as this counter is broken you need to check your logs.
Search for "GmsGcmMcsInput". You should see the heartbeat and Incoming message. In the incoming message part there should be a category stating the telegram package. Then you should be quite sure that telegram is receiving the messages via GCM.
If it is not there, probably you are still in some polling mode and should uninstall/reinstall (I'll update #439 with a description on what to do on reinstall).
If it is there, you probably need to look for other problems, like wakelocks, etc.

**Comment by theel0ja** [comment] 2018-09-07 11:34
You should use Telegram-FOSS from F-Droid.

https://f-droid.org/packages/org.telegram.messenger/
https://github.com/Telegram-FOSS-Team/Telegram-FOSS

**Comment by cRaZy-bisCuiT** [comment] 2018-09-07 13:40
@theel0ja Thanks, but no. Massive battery drain for me and Telegram upstream client used to work well.

**Comment by starbrights** [comment] 2018-09-21 07:42
I am confused. Some recommened use older Telegram (including GCM), some say that version in FDroid (despite which version) doesn't include GCM at all. 
As far as I understand, this GCM support it needed for on time messaging/incoming calls when used microG. 
So - whats true?

**Comment by theel0ja** [comment] 2018-09-21 12:43
@starbrights
Telegram published on F-Droid is not using GCM/FCM (or any other proprietary dependency). It's [Telegram-FOSS](https://github.com/Telegram-FOSS-Team/Telegram-FOSS).

**Comment by Nanolx** [comment] 2018-10-03 17:01
The latest 0.2.6.13280 includes bugfixes regarding GCM, so if for whatever reason you can't use the FOSS version, you may try again with re-installing Telegram after you've updated microG to the latest version.

**Comment by cRaZy-bisCuiT** [comment] 2018-10-05 12:54
@Nanolx Problem seems solved for me. Telegram does check in with FCM as well as really receiving messages.

**Comment by starbrights** [comment] 2018-10-06 05:31
I am on 0.2.6.13280 and can confirm it works great. Not sure which version of telegram I have installed.
Ok, in settings I see: Telegram-FOSS 4.9.1 - so its from FDroid, right?

**Comment by Nanolx** [comment] 2018-10-06 19:17
@starbrights yup, that's the F-Droid version.

Great work from @mar-v-in to solve outermost GCM issues.

**Comment by godoftech** [comment] 2018-10-11 16:13
Possible workaround:
https://github.com/microg/android_packages_apps_GmsCore/issues/631#issuecomment-429013399

**Comment by ale5000-git** [comment] 2019-06-02 14:10
The problem should be fixed in recent versions of microG GmsCore, I'm closing this for now.
Please try it and report back.

**Closed by ale5000-git** 2019-06-02 14:10 UTC
Labels: ☁️ Cloud / Push Messaging
