### ISSUE TITLE
Suggestion/Feature request - microG should really be just a single flashable zip file for it to flawlessly work and become a wise succes

### ISSUE THREAD

**Issue by uncertainquark** [microg/android_packages_apps_GmsCore#240] opened 2016-12-11 10:53 UTC
Just like [OpenGApps](http://opengapps.org/) is a single flashable zip file that makes everything Google Services work, it would be both ideal and familiar to people on the custom ROM side. 

We all know that the installation is pretty complicated right now, even for basic things to work (gms core + push notifications + location), so even without Google apps. I understand its no small project and I am extremely glad that such a project exists! But without easy to install processes, it would not gain much traction.

What are the future plans to make the process easier? :)

**Comment by blastagator** [comment] 2016-12-12 23:47
If it becomes "easy" the odds of Google pushing back will exponentially increase.  This project will likely promptly end with the penning of a cease and desist letter by Google.  Right now the number of users is so low, Google probably doesn't care.  If everyone starts using it, we may end up with no one using it.

**Comment by uncertainquark** [comment] 2016-12-13 06:35
Not sure ours would be a sizable audience. The only people who will even care to about such a project is the FOSS enthusiasts. And unfortunately, we know that its not a substantial fraction of the world audience. So I doubt that easing the process a bit would bring Google to act on it.

**Comment by marmistrz** [comment] 2016-12-18 16:32
Is there anything illegal in microG?

**Comment by n76** [comment] 2016-12-18 16:37
"Is there anything illegal in microG?": I am not a lawyer and it is my understanding that laws vary a lot around the world.

That said, it seems to me the only questionable area might be re-implementing the Google APIs (which is needed to replace Google's code). As I understand it there is/has been a lawsuit against Google by Oracle on this point. Seems like Google would have a hard time claiming both sides of that argument in different cases and would much rather win the case against Oracle than pursue the point against microG.

**Comment by blastagator** [comment] 2016-12-18 16:52
"illegal" is different than violating the ToS.  I believe using this type of access of Google services violates the ToS.  That said, if this is a ToS violation, there is also a case to be made that this type of access could fall under 18 U.S. Code § 1030, as unauthorized access of a computer system, which is a crime.  I know of no case of this type (ToS violation as a crime) but that doesn't mean it isn't technically possible.

The law is grey as to if this is technically criminal.  You should not construe these thoughts as a legal opinion.

**Comment by Nutomic** [comment] 2016-12-29 10:17
Duplicate of #196

**Comment by Lanchon** [comment] 2016-12-29 13:02
@blastagator,

no such "unauthorized access" would hold water unless you are doing something with the service that you are not allowed to do with google tools. plus no big company would push such a thing if they could because of the terrible PR nightmare; what happened with OGwhatsapp, OGyourtube etc?

> the issue with microG is not having copied code

well there is no issue currently. but if it were, it could well be copying code. the API created by google is being reimplemented and thus the "copying".

of course google would loose this one by their own precedent, but nothing stops google from starting legal actions that they would loose. on the other hand, criminal charges cannot be brought on by google, so this kind of thing cannot happen in criminal law.

> This project will likely promptly end with the penning of a cease and desist letter by Google.

the cease and desist letter can be sent without merit, and say any invalid thing that they want. but IMHO the only thing microG would need to actually do to comply with the law is removing the google account support, which is only a lesser important part of the project. the reimplementation of services API required to run 3rd party code is really the center of microG.

**Closed** 2016-12-30 15:57 UTC
Labels: duplicate
