### ISSUE TITLE
Can't add google account on alternative android implementation.

### ISSUE THREAD

**Issue by V10lator** [microg/android_packages_apps_GmsCore#413] opened 2017-08-15 07:01 UTC
I'm using a Jolla C ( https://jolla.com ) which uses aliendalvik ( http://www.myriadgroup.com/en/products/device-solutions/mobile-software/alien-dalvik/ ). On top of that I installed microg as described here: https://www.joachim-breitner.de/blog/713-microG_on_Jolla

This combinations works just fine except for one issue: I have an app which requires a google account linked to the play services. Now I read that this should be doable from android settings but the Jolla / aliendalvik is missing said setting. That said I think it would be great if microg would offer a way to add an account in its own settings.

//EDIT: Forgot to say: In the past I used the original Google Play Services on the same phone and they offered a way to add an account. Anyway, I don't want to use them anymore so I hope this feature request will make it. :)

**Comment by erikderzweite** [comment] 2017-10-21 21:49
I'm using Sailfish X (Sailfish OS on Sony Xperia X). Have installed microg as well using [this tutorial](http://talk.maemo.org/showpost.php?p=1509945&postcount=85). 

Got signature spoofing to work, but adding account is still not possible with alien dalvik. It would be very nice to have this option in microG directly. I know that on Android it works without (previous phone is Oneplus One with LineageOS and microG), but it would be a very nice feature to have in other systems as well.

**Comment by ale5000-git** [comment] 2017-10-21 22:51
@V10lator
@erikderzweite
Try to install microG with PlayStore and add an account through PlayStore, after it you can remove PlayStore and reinstall FakeStore if you want.

**Comment by erikderzweite** [comment] 2017-10-22 10:46
That did work, had to downgrade microg to the stable 0.2.4, but then it worked despite several errors shown.

**Comment by hevanaa** [comment] 2018-09-20 11:35
I have latest microG and have the same problem. I removed FakeStore and installed PlayStore. But when trying to start PlayStore I get the same "microG Services Core" dialog with a SIGN IN button that doesn't work. Otherwise latest microG works great.

**Comment by hevanaa** [comment] 2018-09-21 05:59
@voidstarstar Thanks, sounds exactly right from the description. The Android environment in Alien-Dalvik is 4.4. Hopefully we get an updated version at some point. I need to try an OTG cable (should have one somewhere from my N900 days).

**Comment by hevanaa** [comment] 2018-09-21 19:16
This worked fine with an OTG USB keyboard. I didn't have to install PlayStore. I tried with the Youtube app and was able to add my account.

**Comment by ale5000-git** [comment] 2019-03-10 21:09
Duplicate of #368

It should be fixed in the latest code (it isn't yet released).
Ref: https://github.com/microg/android_packages_apps_GmsCore/commit/ceb7e721b1882b21814cb4333f77f93c0c13ed51

**Comment by ale5000-git** [comment] 2019-03-10 21:15
The problem of the sign in button that doesn't work should be fixed in the latest code (it isn't yet released).
Ref: https://github.com/microg/android_packages_apps_GmsCore/commit/ceb7e721b1882b21814cb4333f77f93c0c13ed51

**Comment by ihusky02** [comment] 2019-03-11 02:56
> The problem of the sign in button that doesn't work should be fixed in the latest code (it isn't yet released).
> Ref: [ceb7e72](https://github.com/microg/android_packages_apps_GmsCore/commit/ceb7e721b1882b21814cb4333f77f93c0c13ed51)

But when will be released, and you need add signature spoffing from android 8.1 to work with SailfishOS alien dalvik

**Comment by ale5000-git** [comment] 2019-04-01 15:24
@ihusky02
About the new release I don't know.
About signature spoofing if you are using Tingle, please open a new issue [here](https://github.com/ale5000-git/tingle/issues) posting the framework.jar (already deodexed).

**Closed** 2019-04-17 15:16 UTC
