### ISSUE TITLE
[Issue] Unable to add Google Account

### ISSUE THREAD

**Issue by devilprince123** [microg/android_packages_apps_GmsCore#779] opened 2019-05-13 21:55 UTC
I set up Micro Gapps in my device. Everything is working fine but when i try to add my google account in Micro Gapps or in any other app like Play Store it show sign in window after adding my email and password it displays terms and conditions page. When i click on accept, its starts loading and it freezes on loading nothing happens it just loading. Anyone plz give me solution to solve this issue.
Thanks in advance.

**Comment by MrDodojo** [comment] 2019-05-14 08:18
Known issue, something wrong with a webview, do you have chrome enabled? Disable it and login and then you can enable chrome again

**Comment by Nanolx** [comment] 2019-05-14 21:01
Duplicate of #770

**Comment by mar-v-in** [comment] 2019-05-25 14:20
Close as duplicate

**Closed by mar-v-in** 2019-05-25 14:20 UTC
Labels: duplicate
