### ISSUE TITLE
Unable to add Google account

### ISSUE THREAD

**Issue by ClayMaster** [microg/android_packages_apps_GmsCore#491] opened 2018-02-27 18:56 UTC
MicroG Services Core is 0.2.4-108.
Wher I try to add Google account:

![screenshot_2018-02-27-21-46-05](https://user-images.githubusercontent.com/36898345/36748355-add7a9b8-1c08-11e8-9e2b-6df2b872a33d.png)

Both buttons "Cancel" and "Sign in" are inactive and cannot be pressed.
Tried on some custom ROMs 4.2.1 and 4.4.2 with same result.

**Comment by ale5000-git** [comment] 2018-02-27 22:06
Duplicate of #368

**Comment by ale5000-git** [comment] 2019-03-10 21:08
It should be fixed in the latest code (it isn't yet released).
Ref: https://github.com/microg/android_packages_apps_GmsCore/commit/ceb7e721b1882b21814cb4333f77f93c0c13ed51

**Comment by ale5000-git** [comment] 2019-06-01 15:06
Bugs is fixed.
New version is out now.

**Closed by ale5000-git** 2019-06-01 15:06 UTC
Labels: duplicate, 👥 Accounts
