### ISSUE TITLE
Google Cloud Messaging doesn't work properly in LineageOS for microG 15.1 (on OnePlus 3T)

### ISSUE THREAD

**Issue by deesnook** [microg/android_packages_apps_GmsCore#502] opened 2018-03-12 22:40 UTC
I've flashed the latest version and it looks like registering for GCM doesn't always work. Some apps have sucessfully registered, others haven't. Consequently, push notifications do not work in the latter cases

Any ideas?

**Comment by maxammann** [comment] 2018-03-16 17:56
Same here, Telegram and Whatsapp in my case

**Comment by jcgruenhage** [comment] 2018-03-18 14:14
Same here, OP3 (non-T). For some reason the banking app I use needs GCM 🙄

**Comment by Generator** [comment] 2018-03-18 16:21
This is a duplicate of #439 

I've manage to register Whatsapp with microG GCM using an older build ([2.17.351](https://www.apkmirror.com/apk/whatsapp-inc/whatsapp/whatsapp-2-17-351-release/)), some newer builds fail to register with microG, probably the same applies to other apps

PS: For Telegram users you can use the [Telegram from F-Droid](https://f-droid.org/packages/org.telegram.messenger/), don't need GCM

**Comment by javeq1** [comment] 2018-03-25 10:06
I have the same problem with an app we use at my work place. 
It used to register correctly with Android 7 (Lineage OS 14) but the same version of the app does not register itself now in android 8.1 (Lineage OS 15).

**Comment by drrossum** [comment] 2018-03-26 13:59
@Generator Do you get push notifications once registered? I did try this some weeks ago, registered to GCM using an old WhatsApp version by changing the system clock and then updated to a newer version that had not yet expired. I never got push notifications for WhatsApp.  The GCM status in the microG app shows "no messages received so far" for WhatsApp.

**Comment by Generator** [comment] 2018-03-26 15:21
@drrossum changing the system clock didn't work here, WhatsApp still notifies to update the app and didn't register GCM, WhatsApp 2.17.351 was the older version that i could install and register GCM, however with newer versions 2.17.351 wont work anymore if you want to install and register GCM, will be a newer version, til the newer versions wont register anymore if the bug isn't fixed.

Still have some apps that couldn't register GCM, and i'm experience some battery drain, cant tell if is related with microG or not, that didn't happen with Android 7.1.2

Tested with:
Android: 8.0.1
WhatsApp: 2.17.351
microG: 2.4.108 (from NanoDroid)

![screenshot_microg_services_core_20180326-160705](https://user-images.githubusercontent.com/44146/37915365-481ff58a-3111-11e8-8b0b-a8ec919f2db9.png)

**Comment by drrossum** [comment] 2018-03-26 15:38
This is what I do, on Lineage 15.1 (8.1)
- backup WA chat
- uninstall WA
- set system clock back in time (before 2018-03-18)
- install WA v2.17.351, do not run WA yet!
- open WA app settings and enable all permissions
- open WA and register user account
- restore chat backup
WA should now register with microG GCM and be able to receive GCM push messages.
If you reset the system clock and WA cries that it's expired, you can do the following:
- change system clock back to before 2018-03-18
- adb install -r whatsapp_2.17.351.apk
- run WA

I'm now trying WA 2.17.395. It looks like it doesn't register but does receive push notifications if WA was registered with v2.17.351.  I need to test this more, though.

**Comment by conrad-heimbold** [comment] 2018-03-27 14:36
logcat?

**Comment by Generator** [comment] 2018-03-29 14:12
Came across this workaround 

> Disable battery optimization (doze) for WhatsApp and you should receive messages without delays

Source: [XDA microG thread](https://forum.xda-developers.com/showpost.php?p=75861151&postcount=4426)  

Didn't test it, but can probably work

**Comment by drrossum** [comment] 2018-03-29 14:23
That should work at the cost of increased battery consumption

**Comment by Tom4tot** [comment] 2018-04-25 22:12
So I tried this workaround from @drrossum : https://github.com/microg/android_packages_apps_GmsCore/issues/502#issuecomment-376210921

And it doesn't work for me, see this post: 
https://forum.xda-developers.com/showpost.php?p=76340601&postcount=849

As this solution "Disable battery optimization (doze) for WhatsApp and you should receive messages without delays": it's not satisfying either from my experience.

**Comment by 1337sup3rh4x0r** [comment] 2018-04-28 16:07
I can confirm the same behavior on my OnePlus 2 using microG LineageOS 15.1 latest weekly build.

Some apps seem to receive notifications sporadically (in my case e.g. signal).

Other apps register fine and are shown in the Google Cloud Messaging List of microG Settings, but never receive any message.

One app (Threema in my case) doesn't even register and doesn't show up in the list.

Is there any specific info we can supply to help understanding the root cause here?

**Comment by ale5000-git** [comment] 2018-06-20 09:32
We shouldn't mix 2 different problems:
1) The switch to FCM that cause problems
2) The delayed messages caused by Doze

The first need FCM support in microG while the second is the one discussed on #338

**Comment by tobiasKaminsky** [comment] 2018-07-16 09:22
We are using 
```
implementation "com.google.firebase:firebase-messaging:12.0.1"
implementation "com.google.android.gms:play-services-gcm:12.0.1"

and our app/device is not registered for push notifications at all.
Downgrading this to 9.6.x is resolving the problem, without any further code changes.

Maybe some other can test this and if this workaround works, I hope it will help the microG dev to find a solution for newer version.

**Comment by godoftech** [comment] 2018-10-11 16:15
Possible workaround:
https://github.com/microg/android_packages_apps_GmsCore/issues/631#issuecomment-429013399

**Comment by ale5000-git** [comment] 2019-06-02 12:45
The problem should be fixed in the new version of microG GmsCore released yesterday, I'm closing this for now.
Please try it and report back.

**Closed by ale5000-git** 2019-06-02 12:45 UTC
Labels: ☁️ Cloud / Push Messaging
