### ISSUE TITLE
High Android OS battery drain caused by LocationManagerService

### ISSUE THREAD

**Issue by tecufanujacu** [microg/android_packages_apps_GmsCore#166] opened 2016-08-04 14:43 UTC
I'm using microg on cm13 and from several months I have an high Android OS battery drain caused by LocationManagerService, what can I do? 
Is there some way to understand precisely why LocationManagerService causes a lot of wakelocks?
I doesn't have any app that uses the Location.
With AppOps I can see that the only apps that continuously  listen the location are Android OS and the backend WiFi Location Service.
I also tried to disable the backend WiFi Location Service but I don't have any difference.

**Comment by n76** [comment] 2016-08-04 15:39
In my experience, high battery drain from GmsCore is more often from the Google Cloud Messaging functionality. There have been some threads on XDA and also, I think, in other issue reports here about that and alternative settings that might reduce the overhead. I haven't paid much attention to them as I haven't noticed that issue on my phone.

The WiFi backend (not actually written or supported by the microG team) is be a "passive" listener for location updates so that it can get GPS locations when other apps enable the GPS. So it should not be using very much power if the GPS is actually off. It does have some work to do when it gets a GPS update (scan for WiFi/WLAN APs and do some calculations to see if it needs to update its database). In addition, apps that request GPS data usually request location information from all sources so they are likely to be requesting network based location through UnifiedNLP or GmsCore. There is some work done by the backend at that time (scan for WiFi/WLAN APs, lookup in database, compute location) but those are relatively cheap operations. I am not surprised that disabling the WiFi backend had little or not effect on your battery drain. If you do find that the WiFi backend is the culprit, please open an issue on the GitHub page for that instead of here.

**Comment by craftyguy** [comment] 2016-08-12 17:44
I don't think it's GCM... It seems like GmsCore is not turning off GPS when it is not needed anymore. It can easily be reproduced on my device (running CM13 nightly 8-11-16) by starting a mapping app (e.g. Maps.me) and closing the app. GPS stays enabled, causing heavy battery drain, until I force-stop GmsCore. It happens with any app I've tried that uses GPS, so I don't think it's app-specific.

I also see this same behavior when I reboot my device, GPS is enabled automatically and consumes battery until force-quitting GmsCore. This is with the latest GmsCore from the MicroG f-droid repo.

**Comment by craftyguy** [comment] 2016-08-12 17:44
I don't think it's GCM... It seems like GmsCore is not turning off GPS when it is not needed anymore. It can easily be reproduced on my device (running CM13 nightly 8-11-16) by starting a mapping app (e.g. Maps.me) and closing the app. GPS stays enabled, causing heavy battery drain, until I force-stop GmsCore. It happens with any app I've tried that uses GPS, so I don't think it's app-specific.

I also see this same behavior when I reboot my device, GPS is enabled automatically and consumes battery until force-quitting GmsCore. This is with the latest GmsCore from the MicroG f-droid repo.

**Comment by n76** [comment] 2016-08-12 17:52
> It seems like GmsCore is not turning off GPS when it is not needed anymore. It can easily be reproduced on my device (running CM13 nightly 8-11-16) by starting a mapping app (e.g. Maps.me) and closing the app. GPS stays enabled,

I am not seeing this with my 6.0.1 AOSP ROM built a few days ago with the August security patches. I wonder if CM is doing something strange in its interaction with GmsCore.

**Comment by craftyguy** [comment] 2016-08-12 17:54
> I am not seeing this with my 6.0.1 AOSP ROM built a few days ago with the August security patches. I wonder if CM is doing something strange in its interaction with GmsCore.

Probably not out of the question... Is there anything useful I can collect/share to help debug this further? I'm wary of posting my full logcat output since it often contains personal/sensitive information, but if there is something specific I can filter on and it would be helpful, let me know!

**Comment by n76** [comment] 2016-08-12 18:01
adb logcat | grep NlpLocationBackendFuser

That should get you information about any time GmsCore (or UnifiedNLP) is getting a position estimate from its backends.

Near as I can tell, GmsCore/UnifiedNLP doesn't directlytouch the GPS subsystem at all. My WiFi backend does a "passive" monitor of the GPS and will update its database and possibly update the network location when there is a new position report from the GPS. So if you are running that backend you may see some interaction between the GPS and GmsCore/UnifiedNLP.

**Comment by craftyguy** [comment] 2016-08-12 18:07
I'm actually using the Mozilla backend.. I wonder if that's the culprit. Anyways, here's the logcat info, though I had no entries for NlpLocationBackendFuser.. I grepped on nlp and gmsloc (my best guess for what might be helpful):

`$ adb logcat -d |grep -i nlp

08-12 10:40:15.032 32531 32542 D GmsLocManagerSvcImpl: updateLocationRequest: LocationRequestUpdateData{opCode=1, request=LocationRequestInternal{request=LocationRequest{priority=100, interval=3000, fastestInterval=1500, explicitFastestInterval=true, expirationTime=9223372036854775807, numUpdates=2147483647, smallestDesplacement=0.0, maxWaitTime=0}, requestNlpDebugInfo=false, restorePendingIntentListeners=true, triggerUpdate=true, clients=[], tag='null', hideFromAppOps=false}, listener=com.google.android.gms.location.ILocationListener$Stub$Proxy@c9e56ce, pendingIntent=null, callback=null, fusedLocationProviderCallback=com.google.android.gms.location.internal.IFusedLocationProviderCallback$Stub$Proxy@f31e9ef}
08-12 10:40:15.104 32531 32543 D GmsLocManagerSvcImpl: updateLocationRequest: LocationRequestUpdateData{opCode=1, request=LocationRequestInternal{request=LocationRequest{priority=100, interval=1000, fastestInterval=500, explicitFastestInterval=true, expirationTime=9223372036854775807, numUpdates=2147483647, smallestDesplacement=0.0, maxWaitTime=0}, requestNlpDebugInfo=false, restorePendingIntentListeners=true, triggerUpdate=true, clients=[], tag='null', hideFromAppOps=false}, listener=com.google.android.gms.location.ILocationListener$Stub$Proxy@68fdf01, pendingIntent=null, callback=null, fusedLocationProviderCallback=com.google.android.gms.location.internal.IFusedLocationProviderCallback$Stub$Proxy@cfa71a6}
08-12 10:40:23.662 32531 32543 D GmsLocManagerSvcImpl: updateLocationRequest: LocationRequestUpdateData{opCode=1, request=LocationRequestInternal{request=LocationRequest{priority=104, interval=60000, fastestInterval=10000, explicitFastestInterval=false, expirationTime=9223372036854775807, numUpdates=2147483647, smallestDesplacement=0.0, maxWaitTime=0}, requestNlpDebugInfo=false, restorePendingIntentListeners=true, triggerUpdate=true, clients=[], tag='null', hideFromAppOps=false}, listener=com.google.android.gms.location.ILocationListener$Stub$Proxy@dbdc18c, pendingIntent=null, callback=null, fusedLocationProviderCallback=com.google.android.gms.location.internal.IFusedLocationProviderCallback$Stub$Proxy@90c40d5}
`

`adb logcat -d |grep -i gmsloc

08-12 10:40:23.639 32531 32543 D GmsLocManagerSvc: bound by: GetServiceRequest{serviceId=LOCATION_MANAGER, gmsVersion=8487000, packageName='com.mapswithme.maps.pro', extras=Bundle[{client_name=locationServices}]}
08-12 10:40:23.643 32531 32545 D GmsLocManagerSvc: bound by: GetServiceRequest{serviceId=LOCATION_MANAGER, gmsVersion=8487000, packageName='com.mapswithme.maps.pro', extras=Bundle[{client_name=locationServices}]}
08-12 10:40:23.644 32531 32542 D GmsLocManagerSvcImpl: getLastLocationWithPackage: com.mapswithme.maps.pro
08-12 10:40:23.662 32531 32543 D GmsLocManagerSvcImpl: updateLocationRequest: LocationRequestUpdateData{opCode=1, request=LocationRequestInternal{request=LocationRequest{priority=104, interval=60000, fastestInterval=10000, explicitFastestInterval=false, expirationTime=9223372036854775807, numUpdates=2147483647, smallestDesplacement=0.0, maxWaitTime=0}, requestNlpDebugInfo=false, restorePendingIntentListeners=true, triggerUpdate=true, clients=[], tag='null', hideFromAppOps=false}, listener=com.google.android.gms.location.ILocationListener$Stub$Proxy@dbdc18c, pendingIntent=null, callback=null, fusedLocationProviderCallback=com.google.android.gms.location.internal.IFusedLocationProviderCallback$Stub$Proxy@90c40d5}
08-12 10:40:23.663 32531 32543 D GmsLocProviderReal: network: addRequest LocationRequestHelper{locationRequest=LocationRequest{priority=104, interval=60000, fastestInterval=10000, explicitFastestInterval=false, expirationTime=9223372036854775807, numUpdates=2147483647, smallestDesplacement=0.0, maxWaitTime=0}, hasFinePermission=true, hasCoarsePermission=true, packageName='null', lastReport=null}
08-12 10:40:23.663 32531 32543 D GmsLocProviderReal: network: requesting location updates. minTime=1000 minDistance=0.0
08-12 10:40:25.168 32531 32546 D GmsLocManagerSvcImpl: addGeofences: com.google.android.gms.location.GeofencingRequest@fb6b0ea
08-12 10:45:56.841  2515  2515 D GmsLocManagerSvc: onBind: Intent { act=com.google.android.location.internal.GoogleLocationManagerService.START pkg=com.google.android.gms }
08-12 10:45:56.852  2515  2527 D GmsLocManagerSvc: bound by: GetServiceRequest{serviceId=LOCATION_MANAGER, gmsVersion=8487000, packageName='com.mapswithme.maps.pro', extras=Bundle[{client_name=locationServices}]}
08-12 10:45:56.852  2515  2528 D GmsLocManagerSvc: bound by: GetServiceRequest{serviceId=LOCATION_MANAGER, gmsVersion=8487000, packageName='com.mapswithme.maps.pro', extras=Bundle[{client_name=locationServices}]}
08-12 10:46:01.708  2515  2528 D GmsLocManagerSvc: bound by: GetServiceRequest{serviceId=LOCATION_MANAGER, gmsVersion=6587000, packageName='ch.gridvision.ppam.androidautomagic', extras=Bundle[{client_name=locationServices}]}
08-12 10:46:01.714  2515  2529 D GmsLocManagerSvcImpl: addGeofences: com.google.android.gms.location.GeofencingRequest@2d26793
08-12 10:55:26.000  2515  2527 D GmsLocManagerSvcImpl: removeGeofencesById: [RADIUS_ZONE]
08-12 10:55:26.002  2515  2528 D GmsLocManagerSvcImpl: addGeofences: com.google.android.gms.location.GeofencingRequest@dd713d0
08-12 10:58:37.282  2515  2530 D GmsLocManagerSvcImpl: removeGeofencesById: [RADIUS_ZONE]
08-12 10:58:37.285  2515  2528 D GmsLocManagerSvcImpl: addGeofences: com.google.android.gms.location.GeofencingRequest@f7cffc9
`

**Comment by n76** [comment] 2016-08-12 19:53
Looks like you have something that is setting up a geo fence. I wonder if that is causing the GPS to be accessed a lot.

**Comment by craftyguy** [comment] 2016-08-12 20:15
I have Automagic Premium implementing geofencing for some tasks, however I've had this app for several years and haven't really modified any of the geofencing stuff. Disabling the service doesn't free up GPS though, microG seems to still have it on until I force-stop it. Maybe it's the backend.. I'm going to switch to your Wifi backend NLP to see if that resolves it for me :)

**Comment by n76** [comment] 2016-08-12 20:19
Having read the source code for the other backends, I doubt that changing to my WiFi backend will alter the symptoms you are seeing.

Also, my backend learns when the GPS is on. It starts out knowing nothing and then builds its database when other apps turn on the GPS. The result is that until you have built up a reasonable local database, that backend may not be as useful as you'd like.

**Comment by craftyguy** [comment] 2016-08-12 20:25
It looked promising, probably because your backend does not actively turn on GPS (my understanding of how these backends work is admitedly very primative..), however I can easily reproduce this by disabling any apps that may implement a geofence and performing a reboot of the device. When it comes back up, GPS is enabled and microG is a big battery user.

**Comment by mar-v-in** [comment] 2016-08-12 23:49
Geofences are not causing the problem as they are not yet implemented in GmsCore.

@craftyguy the log you provided does not show any gps requests by GmsCore, can you start the logging process directly after boot before killing GmsCore the first time?

**Comment by craftyguy** [comment] 2016-08-13 00:11
So funny story, I switched NLP backend from Mozilla to local GSM and local wifi backends (enabled at same time, because I have no idea what I'm doing and it seemed like a good idea). I cannot reproduce the issue I was seeing anymore after a reboot. I'll continue testing a report back with logcat info if I see it again. 

This may or may not be related to the issue originally reported.. I thought it was related when I first commented, so OP please report back if you see different behavior...

**Comment by tecufanujacu** [comment] 2016-08-13 15:53
Yes my problem is different and I don't anymore think that it is caused by microg or its backends because after a factory reset and a lot of tests I tried to use a different carrier and the problem has disappeared so I'm pretty sure that it is related to my actual carrier and for this I'm sorry for opening this issue, I think that this can be closed.

**Closed** 2016-08-13 18:25 UTC
