### ISSUE TITLE
mapbox: unimplemented Method: addPolygon

### ISSUE THREAD

**Issue by Torvin** [microg/android_packages_apps_GmsCore#851] opened 2019-06-25 09:19 UTC
Local bicycle app started to crash upon opening with this:

```
             SafeParcel  D  Unknown field num 10 in com.google.android.gms.maps.model.PolygonOptions, skipping.
                         D  Unknown field num 11 in com.google.android.gms.maps.model.PolygonOptions, skipping.
                 GmsMap  D  unimplemented Method: addPolygon
         AndroidRuntime  D  Shutting down VM
                         E  FATAL EXCEPTION: main
                         E  Process: com.bicycle.app, PID: 31102
                         E  java.lang.NullPointerException: null reference
                         E  	at com.google.android.gms.common.internal.zzbo.zzu(Unknown Source:7)
                         E  	at com.google.android.gms.maps.model.Polygon.<init>(Unknown Source:3)
                         E  	at com.google.android.gms.maps.GoogleMap.addPolygon(Unknown Source:8)
                         E  	at com.google.maps.android.data.Renderer.addPolygonToMap(Renderer.java:682)
                         E  	at com.google.maps.android.data.Renderer.addGeoJsonFeatureToMap(Renderer.java:505)
                         E  	at com.google.maps.android.data.Renderer.addFeature(Renderer.java:446)
                         E  	at com.google.maps.android.data.geojson.GeoJsonRenderer.addFeature(GeoJsonRenderer.java:62)
                         E  	at com.google.maps.android.data.geojson.GeoJsonRenderer.addLayerToMap(GeoJsonRenderer.java:51)
                         E  	at com.google.maps.android.data.Layer.addGeoJsonToMap(Layer.java:61)
                         E  	at com.google.maps.android.data.geojson.GeoJsonLayer.addLayerToMap(GeoJsonLayer.java:103)
                         E  	at com.bicycle.app.activity.MainActivity$11.onPostExecute(MainActivity.java:994)
                         E  	at com.bicycle.app.activity.MainActivity$11.onPostExecute(MainActivity.java:968)
                         E  	at android.os.AsyncTask.finish(AsyncTask.java:695)
                         E  	at android.os.AsyncTask.-wrap1(Unknown Source:0)
                         E  	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
                         E  	at android.os.Handler.dispatchMessage(Handler.java:106)
                         E  	at android.os.Looper.loop(Looper.java:164)
                         E  	at android.app.ActivityThread.main(ActivityThread.java:6494)
                         E  	at java.lang.reflect.Method.invoke(Native Method)
                         E  	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
                         E  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by mar-v-in** [comment] 2019-06-28 21:56
Duplicate of #835

**Closed by mar-v-in** 2019-06-28 21:56 UTC
