### ISSUE TITLE
GMSCore not in F-Droid repository anymore?

### ISSUE THREAD

**Issue by olamma** [microg/android_packages_apps_GmsCore#137] opened 2016-05-22 15:15 UTC
Somehow I am unable to find the GMSCore application in the microG repository on F-Droid. I only see the FakeStore, GFS and Location framework. Is this a problem on my end perhaps? I'd prefer to get it from F-Droid rather than downloading it from here, to have it automatically updated.

**Comment by ibleedbinari** [comment] 2016-05-22 15:25
It is in the microG F-Droid repo, not the main one. You can find it here: https://microg.org/download.html

**Comment by n76** [comment] 2016-05-22 16:10
On my phone, GmsCore shows up as “µg UnifiedNlp (no GAPPS)” with a version of 0.2.3 and shows being installed from “Repository: microG F-Droid repo”.

While it says UnifiedNlp, it definitely is GmsCore as the settings have check boxes for enabling device checkin and the about says “About microG Services Core”

**Comment by ibleedbinari** [comment] 2016-05-22 16:12
Forgot to mention that. Thanks @n76. If you have the main repository enabled, they get merged because they both have the package name of com.google.android.gms. Just pick the versions from the microG repo.

**Comment by olamma** [comment] 2016-05-22 18:29
I actually found the cause of this weird behaviour (UnifiedNlp showing up instead of GMSCore, GMSCore not found in the F-Droid list anymore. Apparently, GMSCore was recently moved from the MicroG repository to the MicroG archive repository. After adding this archive repository, it won't bug out like this anymore and F-Droid will not show UnifiedNlp anymore. My guess is that you also wouldn't receive updates to GMSCore if you don't add this archive repository, which it is in now.

**Comment by mar-v-in** [comment] 2016-05-27 09:56
@olamma the problem is that the F-Droid client can not properly handle mutliple different apps with same package name from different repos. This leads to a merge of UnifiedNlp and GmsCore. The name shown depends on the update date of the corresponding packages in repos and thus can "randomly" change overtime. However updates for UnifiedNlp are actually updates for GmsCore if the microG repo is active.

**Closed by mar-v-in** 2016-05-27 09:56 UTC

**Comment by Nuc1eoN** [comment] 2016-08-09 16:25
Is there a bug report on the F-Droid bugtracker for this?
This is actually a pretty annoying issue..

**Comment by mar-v-in** [comment] 2016-08-09 16:36
The issue is not tracked in the bugtracker afaik, go and create one :)
