### ISSUE TITLE
java.lang.UnsupportedOperationException: Can't convert to color: type=0x2

### ISSUE THREAD

**Issue by whyteks** [microg/android_packages_apps_GmsCore#354] opened 2017-03-27 14:44 UTC
Since 0.2.4 (release):

SettingsActivity Crashes on selecting anything.
I hoped to be able to track it down a little more, but searching 
_java.lang.UnsupportedOperationException: Can't convert to color: type=0x2_
leads down a rabbit hole that goes beyond by current knowledge of Android. :(
This is an Asus K011, Android 4.4.2 so API 19.

```
I/ActivityManager( 3449): START u0 {cmp=com.google.android.gms/org.microg.gms.ui.AboutFragment$AsActivity} from pid 10309
D/WindowManager( 3449): adjustConfigurationLw, config:{1.0 ?mcc?mnc ?locale ?layoutDir sw600dp w600dp h888dp 213dpi lrg port ?uimode ?night finger -keyb/v/h -nav/v} mLidState:1 mHasDockFeature:false mHasKeyboardFeature:false mHasHallSensorFeature:true config.hardKeyboardHidden:2
W/ResourceType(10309): Too many attribute references, stopped at: 0x010104aa
W/ResourceType(10309): Too many attribute references, stopped at: 0x010104ab
D/AndroidRuntime(10309): Shutting down VM
W/dalvikvm(10309): threadid=1: thread exiting with uncaught exception (group=0x9bfcc160)
I/Xposed  ( 3449): FakeGApps: returning fake signature to com.google.android.gms
E/AndroidRuntime(10309): FATAL EXCEPTION: main
E/AndroidRuntime(10309): Process: com.google.android.gms, PID: 10309
E/AndroidRuntime(10309): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.google.android.gms/org.microg.gms.ui.AboutFragment$AsActivity}: android.view.InflateException: Binary XML file line #24: Error inflating class org.microg.tools.ui.SwitchBar
E/AndroidRuntime(10309):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2318)
E/AndroidRuntime(10309):        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2396)
E/AndroidRuntime(10309):        at android.app.ActivityThread.access$800(ActivityThread.java:139)
E/AndroidRuntime(10309):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1293)
E/AndroidRuntime(10309):        at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(10309):        at android.os.Looper.loop(Looper.java:149)
E/AndroidRuntime(10309):        at android.app.ActivityThread.main(ActivityThread.java:5257)
E/AndroidRuntime(10309):        at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(10309):        at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(10309):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:788)
E/AndroidRuntime(10309):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:604)
E/AndroidRuntime(10309):        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
E/AndroidRuntime(10309):        at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime(10309): Caused by: android.view.InflateException: Binary XML file line #24: Error inflating class org.microg.tools.ui.SwitchBar
E/AndroidRuntime(10309):        at android.view.LayoutInflater.createView(LayoutInflater.java:620)
E/AndroidRuntime(10309):        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
E/AndroidRuntime(10309):        at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
E/AndroidRuntime(10309):        at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
E/AndroidRuntime(10309):        at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
E/AndroidRuntime(10309):        at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631)
E/AndroidRuntime(10309):        at android.view.LayoutInflater.inflate(Native Method)
E/AndroidRuntime(10309):        at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
E/AndroidRuntime(10309):        at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
E/AndroidRuntime(10309):        at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:288)
E/AndroidRuntime(10309):        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:143)
E/AndroidRuntime(10309):        at org.microg.tools.ui.AbstractSettingsActivity.onCreate(AbstractSettingsActivity.java:21)
E/AndroidRuntime(10309):        at android.app.Activity.performCreate(Activity.java:5411)
E/AndroidRuntime(10309):        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
E/AndroidRuntime(10309):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2270)
E/AndroidRuntime(10309):        ... 12 more
E/AndroidRuntime(10309): Caused by: java.lang.reflect.InvocationTargetException
E/AndroidRuntime(10309):        at java.lang.reflect.Constructor.constructNative(Native Method)
E/AndroidRuntime(10309):        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
E/AndroidRuntime(10309):        at android.view.LayoutInflater.createView(LayoutInflater.java:594)
E/AndroidRuntime(10309):        ... 26 more
E/AndroidRuntime(10309): Caused by: android.view.InflateException: Binary XML file line #21: Error inflating class TextView
E/AndroidRuntime(10309):        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:713)
E/AndroidRuntime(10309):        at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
E/AndroidRuntime(10309):        at android.view.LayoutInflater.inflate(LayoutInflater.java:462)
E/AndroidRuntime(10309):        at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
E/AndroidRuntime(10309):        at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631)
E/AndroidRuntime(10309):        at android.view.LayoutInflater.inflate(Native Method)
E/AndroidRuntime(10309):        at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
E/AndroidRuntime(10309):        at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
E/AndroidRuntime(10309):        at org.microg.tools.ui.SwitchBar.<init>(SwitchBar.java:69)
E/AndroidRuntime(10309):        ... 29 more
E/AndroidRuntime(10309): Caused by: java.lang.UnsupportedOperationException: Can't convert to color: type=0x2
E/AndroidRuntime(10309):        at android.content.res.TypedArray.getColor(TypedArray.java:327)
E/AndroidRuntime(10309):        at android.content.res.XResources$XTypedArray.getColor(XResources.java:889)
E/AndroidRuntime(10309):        at android.widget.TextView.<init>(TextView.java:703)
E/AndroidRuntime(10309):        at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:62)
E/AndroidRuntime(10309):        at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:58)
E/AndroidRuntime(10309):        at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:103)
E/AndroidRuntime(10309):        at android.support.v7.app.AppCompatDelegateImplV9.createView(AppCompatDelegateImplV9.java:1021)
E/AndroidRuntime(10309):        at android.support.v7.app.A
W/ActivityManager( 3449):   Force finishing activity com.google.android.gms/org.microg.gms.ui.SettingsActivity
```

**Comment by mar-v-in** [comment] 2017-03-27 17:28
duplicate of #267

**Closed by mar-v-in** 2017-03-27 17:28 UTC
