### ISSUE TITLE
YouTube Brand Account not passing Watch History updates

### ISSUE THREAD

**Issue by el3gy** [microg/android_packages_apps_GmsCore#680] opened 2018-12-11 08:10 UTC
Watching videos on MicroG YouTube Apps will not update YouTube's Watch History if the account being used is a Brand Account.

Repro: Sign in with a Brand Account on a MicroG YouTube app (I'm using YouTube Vanced, but probably try others as well), watch a video or two, and check your Watch History.

This isn't super urgent, but it's annoying if you like YouTube Vanced, Watch History, and Not Using your Real Name on YouTube™ equally. Apologies if it's a known issue, and I'm also kinda taking Vanced at their word that it's not their fault.

**Comment by ildar** [comment] 2018-12-11 08:58
what keeps you from leaving YT for NewPipe?

**Comment by el3gy** [comment] 2019-01-18 22:16
> what keeps you from leaving YT for NewPipe?

This is irrelevant; Newpipe doesn't use MicroG and avoids this problem by not implementing user accounts or the ability to cast a video.

As for why I don't use Newpipe, I prefer my YouTube with a bit of functionality.

**Comment by Incog5** [comment] 2019-02-27 16:28
same problem, would love a fix!

**Comment by MrDodojo** [comment] 2019-03-12 21:28
It's fixed! SInce big G is shutting down G+

**Comment by SpectralKH** [comment] 2019-03-12 21:36
@mrDodojo Why would that be related?

**Comment by MrDodojo** [comment] 2019-03-12 21:37
> @MrDodojo Why would that be related?

Because the whole Brand account thing was a G+ thing

**Comment by SpectralKH** [comment] 2019-03-12 21:41
@mrDodojo Highly doubt that. If so, those accounts would be managed through Google Plus, which they are not. It's a separate thing that works with Google+, but also YouTube, Google Photos and maybe more.

**Comment by MrDodojo** [comment] 2019-03-12 21:58
> @MrDodojo Highly doubt that. If so, those accounts would be managed through Google Plus, which they are not. It's a separate thing that works with Google+, but also YouTube, Google Photos and maybe more.

Tho strangely the issue got fixed on the day brand account got a YouTube ONLY feature since G+ is down   soon

**Comment by MrDodojo** [comment] 2019-03-12 21:59
Aka Google is removing the mess they created with G+

**Comment by el3gy** [comment] 2019-03-13 19:47
> It's fixed! SInce big G is shutting down G+

Not fixed. Using latest version of MicroG Services Core and latest version of YouTube Vanced, same problem still, with same repro steps.

I even moved my channel temporarily to test that non-brand account watch history is synced properly, which it is.

>Tho strangely the issue got fixed on the day brand account got a YouTube ONLY feature since G+ is down soon

Youtube has allowed you to unlink a Google+ account for quite some time, and I already had long before opening this issue.

**Comment by MrDodojo** [comment] 2019-03-13 19:48
> > It's fixed! SInce big G is shutting down G+
> 
> Not fixed. Using latest version of MicroG Services Core and latest version of YouTube Vanced, same problem still, with same repro steps.
> 
> I even moved my channel temporarily to test that non-brand account watch history is synced properly, which it is.
> 
> > Tho strangely the issue got fixed on the day brand account got a YouTube ONLY feature since G+ is down soon
> 
> Youtube has allowed you to unlink a Google+ account for quite some time, and I already had long before opening this issue.

Their BRAND account issue is fixed. No the adblocked and other (way too complicated stuff) isn't fixed yet

**Comment by el3gy** [comment] 2019-03-13 20:04
> Their BRAND account issue is fixed. No the adblocked and other (way too complicated stuff) isn't fixed yet

Ads are blocked just fine. **This issue** is that, when using MicroG Core Services, YouTube watch history is not recorded for brand accounts.

I'm not sure what issue _you're_ talking about, but I'm glad that _it's_ fixed. The one this thread is about still isn't.

**Comment by MrDodojo** [comment] 2019-03-13 20:58
> > Their BRAND account issue is fixed. No the adblocked and other (way too complicated stuff) isn't fixed yet
> 
> Ads are blocked just fine. **This issue** is that, when using MicroG Core Services, YouTube watch history is not recorded for brand accounts.
> 
> I'm not sure what issue _you're_ talking about, but I'm glad that _it's_ fixed. The one this thread is about still isn't.

Straaange.................. I'm one of the YouTube Vanced Testers, Translators and Reddit moderators and a big part of our community said history on brand accounts started working again. And I was talking about an adblocker(and or virus scanner or other modification) on your phone blocking history tracking on YouTube.

**Comment by Incog5** [comment] 2019-03-13 21:12
I can confirm watch history is working after the following:
Updated to new vanced version 14.10.53
Clear user data for app MicroG version 0.2.4-105

**Comment by MrDodojo** [comment] 2019-03-13 21:13
> I can confirm watch history is working after the following:
> Updated to new vanced version 14.10.53
> Clear user data for app MicroG version 0.2.4-105

Now there are only 2 major Vanced bugs that need fixing noice

**Comment by el3gy** [comment] 2019-03-13 21:24
Confirmed! Thanks for steps, @Incog5.

And sorry for getting smarmy over my own misunderstanding, @MrDodojo.

Now to go complain about Chromecast support...

**Comment by MrDodojo** [comment] 2019-03-13 21:25
> Now to go complain about Chromecast support...

MVP cast stuff is fixing that in the future and no I should've said that better too

**Closed** 2019-03-13 21:24 UTC

**Comment by dehardstyler** [comment] 2019-03-19 10:08
> @Incog5 It doesn't work with me. I have even removed and reinstalled both microG and Vanced latest version, no success

Over here it's working. Are you sure you are updated to 14.10.53?

**Comment by Rings4** [comment] 2019-04-09 10:26
How come the latest versions of YouTube Vanced (14.06.54 and 14.10.53) require android 4.4+? The older versions required 4.2+. My tablet is on android 4.2.1 and I cannot update my YouTube Vanced 13.37.52 to 14.x because of this :/
Works like a charm on my phone but I use my tablet exclusively for YouTube every single night. I would have loved to be able to FINALLY ditch the official app and start using Vanced but as it stands I still can't!

**Comment by MrDodojo** [comment] 2019-04-09 19:00
> How come the latest versions of YouTube Vanced (14.06.54 and 14.10.53) require android 4.4+? The older versions required 4.2+. My tablet is on android 4.2.1 and I cannot update my YouTube Vanced 13.37.52 to 14.x because of this :/
> Works like a charm on my phone but I use my tablet exclusively for YouTube every single night. I would have loved to be able to FINALLY ditch the official app and start using Vanced but as it stands I still can't!

youtube stopped support.

**Comment by ale5000-git** [comment] 2019-04-10 07:50
There is [NewPipe Legacy](https://f-droid.org/en/packages/org.schabi.newpipelegacy/) that works on Android 4.1+

**Comment by Rings4** [comment] 2019-04-10 07:52
Oh cool, NewPipe Legacy works with YouTube accounts? I had no idea, I'll check it out tomorrow!

**Comment by MrDodojo** [comment] 2019-04-10 07:53
> There is [NewPipe Legacy](https://f-droid.org/en/packages/org.schabi.newpipelegacy/) that works on Android 4.1+

Yup, there is a chance youtube will be releasing one last api 17 version.
Sadly you can't log in in NewPipe xD

**Comment by ale5000-git** [comment] 2019-04-10 07:53
No, no account, but you can see videos and listen music without ads.

**Comment by Rings4** [comment] 2019-04-10 07:54
Oh, if there's no account I'm not interested. Hence why I'm using Vanced..

**Comment by ale5000-git** [comment] 2019-04-10 07:56
But still you can import subscriptions from Youtube and export to file.

**Comment by Rings4** [comment] 2019-04-10 07:58
And have it reflect on my actual youtube account? How about likes, watch history, playlists? Can I comment?

**Comment by ale5000-git** [comment] 2019-04-10 08:00
There are only things that are kept local on the phone, nothing that allow Google to track you, it has a different philosophy.

**Comment by Rings4** [comment] 2019-04-10 08:02
So it's useless to me. I'm interested in Vanced, not NewPipe. I like to unwind on the youtube app, not manage all sorts of things to have a fraction of the functionality the official youtube app or vanced already does.

**Comment by dehardstyler** [comment] 2019-04-10 08:08
> So it's useless to me. I'm interested in Vanced, not NewPipe. I like to unwind on the youtube app, not manage all sorts of things to have a fraction of the functionality the official youtube app or vanced already has.

Then maybe you should start using newer software, instead of using software over 5 years old and then start complaining about all kinds of issues you may or may not have.

**Comment by Rings4** [comment] 2019-04-10 08:11
> 
> 
> > So it's useless to me. I'm interested in Vanced, not NewPipe. I like to unwind on the youtube app, not manage all sorts of things to have a fraction of the functionality the official youtube app or vanced already has.
> 
> Then maybe you should start using newer software, instead of using software over 5 years old and then start complaining about all kinds of issues you may or may not have.

How exactly are you posting this thinking you're being helpful? Or were you offering to buy me a new device so I can use the latest version of youtube vanced? :)

**Comment by ale5000-git** [comment] 2019-04-10 08:12
Well, there isn't a solution, it doesn't make sense to start a discussion.

**Comment by Rings4** [comment] 2019-04-10 08:13
> 
> 
> Well, there isn't a solution, it doesn't make sense to start a discussion.

Then why did you do just that? I had already accepted that youtube dropped support for android 4.2 with MrDodojo's reply.

**Comment by dehardstyler** [comment] 2019-04-10 08:19
> > > So it's useless to me. I'm interested in Vanced, not NewPipe. I like to unwind on the youtube app, not manage all sorts of things to have a fraction of the functionality the official youtube app or vanced already has.
> > 
> > 
> > Then maybe you should start using newer software, instead of using software over 5 years old and then start complaining about all kinds of issues you may or may not have.
> 
> How exactly are you posting this thinking you're being helpful? Or were you offering to buy me a new device so I can use the latest version of youtube vanced? :)

I'm not here to help you, I just think you act like a spoiled child and ale5000 tries to help you. In return to that you are just complaining and saying how you are not interested in this or that. Then start spending some money, and buy a new tablet. 💃

**Comment by Rings4** [comment] 2019-04-10 08:22
> 
> 
> > > > So it's useless to me. I'm interested in Vanced, not NewPipe. I like to unwind on the youtube app, not manage all sorts of things to have a fraction of the functionality the official youtube app or vanced already has.
> > > 
> > > 
> > > Then maybe you should start using newer software, instead of using software over 5 years old and then start complaining about all kinds of issues you may or may not have.
> > 
> > 
> > How exactly are you posting this thinking you're being helpful? Or were you offering to buy me a new device so I can use the latest version of youtube vanced? :)
> 
> I'm not here to help you, I just think you act like a spoiled child and ale5000 tries to help you. In return to that you are just complaining and saying how you are not interested in this or that. Then start spending some money, and buy a new tablet. 💃

How in god's name do you think I'm acting like a spoiled child? I asked a simple question and got my answer. Is stating that I am not interested in newpipe what you're talking about? Please grow up.

**Comment by dehardstyler** [comment] 2019-04-10 08:24
> Please grow up.

Right back at you, sir!
