### ISSUE TITLE
BankID säkerhetsapp-GmsCore-v0.2.7.17455

### ISSUE THREAD

**Issue by vildevilde** [microg/android_packages_apps_GmsCore#824] opened 2019-06-06 21:52 UTC
BankID säkerhetsapp, Swedish app for elektronic identification.

BankID doesn't connect and are useless with last update GmsCore-v0.2.7.17455.

Same problem on two phones running LOS w MicroG,  Google Pixel (Sailfish) LOS 16, and Google Nexus (Bullhead) running LOS 15. Both fully updated same issue. My solution was going back to GmsCore-v0.2.6.13280.

Sorry, I don't know how to make any logs and so, I did found out how to make logs see next entry.

**Comment by vildevilde** [comment] 2019-06-07 06:54
Here follows logfile, while trying to make a new BankID on my bank with BankID app

First one with newest gmscore, GmsCore-v0.2.7.17455, and here BankID fails.
[logcat_newestgmscore.txt](https://github.com/microg/android_packages_apps_GmsCore/files/3264736/logcat_newestgmscore.txt)


Next logfile, is with GmsCore-v0.2.6.13280 and here BankID works.
[logcat_gmscoreold.txt](https://github.com/microg/android_packages_apps_GmsCore/files/3264750/logcat_gmscoreold.txt)

**Comment by pedro-araujo** [comment] 2019-06-07 11:09
Sadly the latest update of BankID broke compatibility with MicroG, I believe it is related to the issue #740.

**Comment by vildevilde** [comment] 2019-06-07 12:55
I do have LOS 16 on Google Pixel and BankID 7.14.0.56, installed yesterday so it should be a newest version and it's working with GmsCore-v0.2.6.13280 but not with GmsCore-v0.2.7.17455

**Comment by roydenyates** [comment] 2019-06-07 22:57
Confirmed LOS 16 on BQ Aquaris X and BankID 7.14.0.56 (latest) - it's working with GmsCore-v0.2.6.13280 but not with GmsCore-v0.2.7.17455.

**Comment by roydenyates** [comment] 2019-06-07 23:13
> Sadly the latest update of BankID broke compatibility with MicroG, I believe it is related to the issue #676.

I think it was the other way round

**Comment by Phydragelit** [comment] 2019-06-10 16:37
(Both devices have BankID v7.14.0.71401 (latest) installed).
BankID säkerhetsapp worked on "OnePlus 3T (oneplus3)" running "LineageOS for microG 16" with "GmsCore-v0.2.6.13280" but "BankID säkerhetsapp" stopped working after system update with "GmsCore-v0.2.7.17455" upgrade. 
Still works on "OnePlus One (bacon)" running "LineageOS for microG 16" with "GmsCore-v0.2.6.13280".
Both devices have working "Google Cloud Messaging" acording to "Push Notication Tester".

Haven't tested going back to older version of "LineageOS for microG 16" on "OnePlus 3T (oneplus3)" with "GmsCore-v0.2.6.13280" yet.

**Comment by churchthecat** [comment] 2019-06-11 18:25
Can confirm the issue on 1+3T

**Comment by ahstro** [comment] 2019-06-15 01:31
Didn't manage to downgrade my OS (and almost botched the backup :sweat_smile: ), so if anyone needs some logs or testing, hmu.

**Comment by oldosfan** [comment] 2019-06-18 00:53
This has probably been fixed with the latest unreleased commits ("Fix calling package detection in KK+"). If BankID crashes with a SecurityException, rest assured that it will be fixed by the next update.

**Comment by ahstro** [comment] 2019-06-19 11:18
BankID doesn't crash, it just loads forever, but I hope that it solves that.

**Comment by churchthecat** [comment] 2019-06-19 11:28
ahstro  you only need to downgrade gmscore not the entire OS. uninstall gmscore from priv-app. Install the older one in priv-app again.

**Comment by ahstro** [comment] 2019-06-19 11:41
@churchthecat, thanks, I'll try that. I'm using microG's LineageOS ROM, so I thought I'd just make it "easy" for me, but easy is never easy, huh. I'll try your solution ASAP. Sorry for diverging the issue thread a bit :innocent:

**Comment by roydenyates** [comment] 2019-06-19 14:11
> @churchthecat, thanks, I'll try that. I'm using microG's LineageOS ROM, so I thought I'd just make it "easy" for me, but easy is never easy, huh. I'll try your solution ASAP. Sorry for diverging the issue thread a bit innocent

If you are  on Lineage OS 17 from Microg and updated the OS a few days back, it updated GmsCore to the problematic v0.2.7.17455 as a system app. This will not uninstall or downgrade on device AFAIK.

**Comment by churchthecat** [comment] 2019-06-19 16:59
I am on linage for microG as well. No problem remove and install it (I used magisk modules debloater and systemizer in termux) just don't update the ROM afterwards as it will install the problematic version again.

**Comment by vildevilde** [comment] 2019-06-19 17:05
> This has probably been fixed with the latest unreleased commits ("Fix calling package detection in KK+"). If BankID crashes with a SecurityException, rest assured that it will be fixed by the next update.

Any idea when this next update will come? is there some way to test this fix before?

**Comment by vildevilde** [comment] 2019-06-20 09:25
On my G Pixel there is a new update today, LOS w MicroG, are there any way safe to update the rom and then roll back microG? Last time it failed to me and I had to reinstall the rom.

**Comment by churchthecat** [comment] 2019-06-20 10:22
all I can say is that it worked for me, but I wait to install any ROM updates until a new version of gmscore is included.

**Comment by roydenyates** [comment] 2019-06-20 11:00
On my phone, the bootloader does not like a rw /system and the OS freezes. That meant magisk etc was useless. BUT, using TWRP I could mount /system rw in a stable way and then use adb to install GsmCore in the older version as a system app (in /system/priv-app/GsmCore/). And it must be a system app for spoofing to work and correct signature.

**Comment by vildevilde** [comment] 2019-06-20 11:04
> On my phone, the bootloader does not like a rw /system and the OS freezes. That meant magisk etc was useless. BUT, using TWRP I could mount /system rw in a stable way and then use adb to install GsmCore in the older version as a system app (in /system/priv-app/GsmCore/). And it must be a system app for spoofing to work and correct signature.

Ok, from being in twrp with system rw, how exactly did you install the older GsmCore with adb?

**Comment by roydenyates** [comment] 2019-06-20 13:19
Easiest is to get the right GmsCore .apk on the device beforehand. Or from PC,
`adb push xxxxx.apk /sdcard/` (choose right apk name, & dir path in place of /sdcard/
then
`adb shell`
`su` (from TWRP you likely should be root anyway)
`rm /system/priv-app/GmsCore/GmsCore.apk` (this removes the installed "problem" version)
`cd /sdcard` (or where you have pushed the xxxx.apk)
`mv xxxxx.apk /system/priv-app/GmsCore/xxxxxx.apk` (replace xxx as appropriate)
`chmod 644 /system/priv-app/GmsCore/xxxxx.apk`

Then unmount system in Twrp and reboot. GmsCore should now be "systemized" at the working version, and microg should show it is working.

**Comment by vildevilde** [comment] 2019-06-20 14:31
> Easiest is to get the right GmsCore .apk on the device beforehand. Or from PC,
> `adb push xxxxx.apk /sdcard/` (choose right apk name, & dir path in place of /sdcard/
> then
> `adb shell`
> `su` (from TWRP you likely should be root anyway)
> `rm /system/priv-app/GmsCore/GmsCore.apk` (this removes the installed "problem" version)
> `cd /sdcard` (or where you have pushed the xxxx.apk)
> `mv xxxxx.apk /system/priv-app/GmsCore/xxxxxx.apk` (replace xxx as appropriate)
> `chmod 644 /system/priv-app/GmsCore/xxxxx.apk`
> 
> Then unmount system in Twrp and reboot. GmsCore should now be "systemized" at the working version, and microg should show it is working.

Thank you, what's the difference from just deleting/removing the files with the filemanager in twrp?

**Comment by roydenyates** [comment] 2019-06-20 14:42
None, I just was in the adb groove :-)

**Comment by vildevilde** [comment] 2019-06-20 15:27
I did it, it worked this time, just replaced the file with twrp filemanager, just as first time I did it, wonder why it didn't work the second time?

**Comment by vildevilde** [comment] 2019-07-04 09:00
There is a new release of GmsCore, since yesterday. v0.2.8.17785, the are two versions,  GmsCore-v0.2.8.17785-mapbox.apk and GmsCore-v0.2.8.17785-vtm.apk. 
Today after a new update with LOS MicroG on Google Pixel (Sailfish) instead of changing back to the old GmsCore-v0.2.6.13280.apk, as I usually do I tried both the new versions but unfortunately I have the same issue as before. BankId is not working and i had to go back to the old version again :(

**Comment by ale5000-git** [comment] 2019-07-09 10:18
Could all of you update to [this build](https://microg.org/dl/GmsCore-v0.2.8.17785-4-06c8b76.apk) and retry please?

@vildevilde: They are more recent then the versions you already tried and also more recent than the last release.

**Comment by vildevilde** [comment] 2019-07-09 13:08
> Could all of you update to [this build](https://microg.org/dl/GmsCore-v0.2.8.17785-4-06c8b76.apk) and retry please?
> 
> @vildevilde: It is more recent then the versions you already tried and also more recent than the last release.

Tried it but no, sorry but not working same issue :(

**Comment by vildevilde** [comment] 2019-07-09 13:19
[logcat_gmscoretest.txt](https://github.com/microg/android_packages_apps_GmsCore/files/3373128/logcat_gmscoretest.txt)

**Comment by vildevilde** [comment] 2019-07-09 16:11
For information I did test the new build from ale5000-git on one other phone, Nexus 5x (bullhead) and LOS 15, same issue BankId is not working.

**Comment by jonjonasson** [comment] 2019-07-25 12:52
Same here. Ale5000-git's version has the same issue. Reverting to GmsCore-v0.2.6.13280.apk by copying to priv-app/GmsCore still works on the 2019-07-22 build of LineageOS.

Can anyone advice on what I can do to help resolve this issue? It's a massive showstopper for most (all) people in Sweden as bankid is used for everyting with high security here!

**Comment by monperrus** [comment] 2019-07-26 18:39
Installed `GmsCore-v0.2.6.13280` and BankId starts well. But no way to register a new login, stalled at the QR-code step (see #670). Any idea?

**Comment by attah** [comment] 2019-07-26 18:46
@monperrus Use a separate qr code reader app, the uri should invoke bankid and let you continue. Worked for me on Sailfish OS at least. (some random android qr code reader was used, native probably wouldn't have done it)

**Comment by churchthecat** [comment] 2019-07-26 18:48
Use a separate qr scanner app , select open in browser and bankid should puck it up from there.

**Comment by monperrus** [comment] 2019-07-26 21:39
It works like a charm with a separate QR-code reader, thanks a lot!

**Comment by pablofsf** [comment] 2019-07-29 20:12
@ale5000-git I don't have the knowledge to fix this issue but I can spend time in bisecting the commits between versions 0.2.6.13280 and 0.2.7.17455 to see which one broke this. Would there be higher chances of getting it fixed if we know the exact commit? I have a Samsung Galaxy S5 with LineageOS for microG install in which I have been able to reproduce the BankID issue by downgrading the version of GmsCore.

In order to try the bisecting, I have actually followed the Building instructions and I have been able  to compile `com.google.android.gms.apk` and `play-services-core-release.apk` from master branch. However, at the time of installing I get the following
```
Failure [INSTALL_FAILED_UPDATE_INCOMPATIBLE: Package com.google.android.gms signatures do not match previously installed version; ignoring!]
```
This gives me the feeling that it might not be secure to directly install a new version. Could you help describing the procedure that should be followed?

Thank you very much for your time

**Comment by chris42** [comment] 2019-07-29 20:47
@pablofsf 
When you compile the apk yourself, it gets another signature than the official ones. You will need to copy it manually on the device as described in a [comment before](https://github.com/microg/android_packages_apps_GmsCore/issues/824#issuecomment-504022645)

**Comment by pablofsf** [comment] 2019-07-30 22:39
Thank you @chris42

So I have a problem because compiling version v0.2.7.17455  and copying to my device gives me a functional BankID app. The process I have followed is:

In my Samsung Galaxy S5 with LineageOS of microG, downloaded and installed the latest system update (from 30th July). At this point BankID is not working

Downloaded from [here](https://developer.android.com/studio/index.html#download) sdk-tools-linux-4333796.zip then:
```bash
export JAVA_HOME=/usr/lib/jvm/default-java
mkdir /opt/android-sdk-update-manager/
mv Downloads/sdk-tools-linux-4333796.zip /opt/android-sdk-update-manager/
cd /opt/android-sdk-update-manager/
unzip sdk-tools-linux-4333796.zip
cd tools/bin
./sdkmanager --licenses # Accept all licenses
cd ~/data/Informatica
mkdir microg
cd microg
mkdir outputs
mkdir keystores
ANDROID_SDK_PATH="/opt/android-sdk-update-manager"
KEYSTORES_PATH="$PWD/keystores"
# Generate keystore
echo "We need to create a keystore for GmsCore:"
keytool -genkey -v -keystore $KEYSTORES_PATH/playservices.jks -alias playservices -keyalg RSA -keysize 4096 -validity 10000
# GMSCore
git clone https://github.com/microg/android_packages_apps_GmsCore.git
cd android_packages_apps_GmsCore
git submodule update --init --recursive
git checkout v0.2.7.17455
git  submodule update --recursive
# Then modified extern/UnifiedNlp/unifiednlp-compat/build.gradle to match android-28
echo "sdk.dir=$ANDROID_SDK_PATH" > local.properties
echo "sdk-location=$ANDROID_SDK_PATH" >> local.properties
./gradlew build
cp play-services-core/build/outputs/apk/release/play-services-core-release-unsigned.apk ../outputs/play-services-core-release.apk
# Sign APK
cd ../outputs
jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore $KEYSTORES_PATH/playservices.jks play-services-core-release.apk playservices
/opt/android-sdk-update-manager/build-tools/28.0.3/zipalign -p -v 4  play-services-core-release.apk com.google.android.gms.apk
```
The file com.google.android.gms.apk is considerably smaller than the ones available in the releases sections (around 12M) and copying it to /system/priv-app/GmsCore/GmsCore.apk makes BankID to work perfectly.

Some more info:
Java version:
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-8u212-b03-0ubuntu1.16.04.1-b03)
OpenJDK 64-Bit Server VM (build 25.212-b03, mixed mode)
OS:
Trisquel 8, based on Ubuntu Xenial

I have also tried compiling master commit instead of v0.2.7.17455, with similar results (generated com.google.android.gms.apk is around 12M and BankID is functional)

Could someone reproduce this behavior?

**Comment by vildevilde** [comment] 2019-07-31 07:55
I don't know how this things work, nor the vocabulary so I don't know how to test, do you have a file I can test, I will do that.

31 juli 2019 00:39:52 +02:00, skrev pablofsf <notifications@github.com>:

**Comment by vildevilde** [comment] 2019-07-31 08:11
I think I did it before, and I tried it again now, the vtm version is not working either.

**Comment by pablofsf** [comment] 2019-07-31 17:24
@vildevilde I have forked the repo and published two [releases](https://github.com/pablofsf/android_packages_apps_GmsCore/releases), one compiled from the last commit of branch master and another one from tag v0.2.7.17455. You should copy the com.google.android.gms.apk to /system/priv-app/GmsCore/GmsCore.apk. If you try them and they are working for you, then either I have done something wrong building them, the building instructions are not updated or the problem is generated during the compile process

**Comment by vildevilde** [comment] 2019-07-31 19:40
Ok, tried both files and none of them works on my LOS16 on Google Pixel

**Comment by pablofsf** [comment] 2019-07-31 22:10
It should be that procedure, although com.google.android.gms.apk is the only file that needs to be tested. At this point I am clueless why it is working for me. You could try this release too, but I doubt it'd make a difference. Sorry for that :(

**Comment by vildevilde** [comment] 2019-08-01 06:19
Sorry, but as you wrote that is not working for me either. I would like somebody else to try so It's not just me doing something wrong.

**Comment by vildevilde** [comment] 2019-08-03 08:12
By removing the microg app completely from the folder my BankId works. There is a warning message, but just ignoring that and it works.

**Comment by klasrocket** [comment] 2019-08-09 08:56
Hi. Thanks for all the work to gather the info in this thread! Just wanted to confirm that I also had the same problem with bankid not working under microG 2.7 but after manual downgrade to 2.6 using twrp I got it back working :)

**Comment by Darkorz** [comment] 2019-08-10 05:45
Samme issue running LOS 16 on a Xiaomi Mi Mix 2. Manual downgrade allows BankID to function but simultaneously breaks notifications for all other apps and leaves you with the outdated/no play services found error. It also seem to disappear the MicroG settings app. Not sure if this is unique to me. I've limited experience with coding, but let me know if I can be of help solving this.

**Comment by vildevilde** [comment] 2019-08-10 08:14
I wonder if there is anyone trying to solve this issue, if not, the I and probably all other Swedish users have to give up the thought of not being forced to use the gogle-shit login. 
As written before, this is **essential** to have BankID working in this country.

**Comment by monperrus** [comment] 2019-08-12 08:42
@pablofsf what are the results of your git bisect?

**Comment by vildevilde** [comment] 2019-08-12 09:01
> @pablofsf what are the results of your git bisect?
I don't understand?

**Comment by monperrus** [comment] 2019-08-12 09:30
>> @pablofsf what are the results of your git bisect?

> I don't understand?

The first step is to identify the commit that introduced the regression. @pablofsf has started to look at this. Once the regression found, the fix should be easy.

**Comment by pablofsf** [comment] 2019-08-12 17:34
@monperrus I might have not been clear, but I bumped into the issue that the versions I compiled run in my phone even if they should not. I have not been able to troubleshoot this issue yet, but I understand it's a problem from my phone's configuration, as BandID did not work with them for @vildevilde

**Comment by vildevilde** [comment] 2019-08-12 20:05
> @monperrus I might have not been clear, but I bumped into the issue that the versions I compiled run in my phone even if they should not. I have not been able to troubleshoot this issue yet, but I understand it's a problem from my phone's configuration, as BandID did not work with them for @vildevilde.
> 
> To make sure that the problem is just in my phone, could @vildevilde check if [this release](https://github.com/pablofsf/android_packages_apps_GmsCore/releases/tag/v0.2.6.13280) makes BankID work (if things are right, it should)?

YES. I got it to work with that file. It took time, I run into a bootloop twice after being in twrp, I had to reinstall two times but I have no idea why. But I'm an amateur on this.

**Comment by vildevilde** [comment] 2019-08-13 14:58
I tested the above file in my Nexus 5x with LOS 15 Microg. Cant get bankid to work with any microg-file, all apps that ned bankiid crash on start. I solved it on that phone as I wrote before, completely remove GmsCore.apk from folder in system, Then I can use Bankid by ignoring the message that it is not working.

**Comment by monperrus** [comment] 2019-08-15 07:45
> I solved it on that phone as I wrote before, completely remove GmsCore.apk from folder in system

I confirm that BankId still works after removing GmsCore (`adb uninstall com.google.android.gms`). It means that GmsCore is not mandatory at runtime.

> Then I can use Bankid by ignoring the message that it is not working

Yes, the message is misleading, it says `Bankid won't run without google play services, which are not supported on your device`, but it actually runs

**Comment by vildevilde** [comment] 2019-08-15 08:46
@pablofsf Today I updated my Google Pixel 1, the last test-file from three days ago works  again.

**Comment by pablofsf** [comment] 2019-08-15 10:20
Ok then what I've been compiling seems to do what it should do. I do not have a lot of time these days, so troubleshooting the problem in my device with the locally compiled files might take me quite a while.  Otherwise, @vildevilde , we could basically do two things if you have the time for it:
- I compile every-single-commit between versions 0.2.6 and 0.2.7, make them available to you. Then you can test them and bisect the commit which introduced the error (do you have experience with git?)
- The other option is to have a meeting in which we can go together through this, so I compile commits, share them with you and you test them later. You can write to my github's email address (ablocorrea@hotmail.com) and we can set a time and date.
If that's not possible, I might be able to troubleshoot the problem I have with my personal device, but I have no idea on how long could that take.

**Comment by vildevilde** [comment] 2019-08-15 11:52
> Ok then what I've been compiling seems to do what it should do. I do not have a lot of time these days, so troubleshooting the problem in my device with the locally compiled files might take me quite a while. Otherwise, @vildevilde , we could basically do two things if you have the time for it:
> 
>     * I compile every-single-commit between versions 0.2.6 and 0.2.7, make them available to you. Then you can test them and bisect the commit which introduced the error (do you have experience with git?)
> 
>     * The other option is to have a meeting in which we can go together through this, so I compile commits, share them with you and you test them later. You can write to my github's email address ([ablocorrea@hotmail.com](mailto:ablocorrea@hotmail.com)) and we can set a time and date.
> 
> 
> If none of the above is possible, I might be able to troubleshoot the problem I have with my personal device, but I have no idea on how long could that take.

@pablofsf It has to be option 2, I have no idea about git, in fact I don't even know what git is really. I am a user not a programmer or anything like that. I send you a mail.

**Comment by an0nkyle** [comment] 2019-08-21 07:38
I'm using microg 0.2.817785 and I tried an qr scanner in f droid for bankid it comes up with this error.
NOTE: I'm using yalp store (its alternative googleplaystore)

"Technical error 134
Try again
If this error remains you may need to remove the BankID security app from your device and try again by installing the app from the Google Play and activating a new BankID from your bank."

**Comment by AsavarTzeth** [comment] 2019-08-21 13:56
Hi all!

This has been a big issue to me for a long time but I never had the time to debug the issue. Today however, I managed to find the bad commit using `git bisect`.

```
725926529a9cbc493535ccaf3f118a30cb01fdd7 is the first bad commit
commit 725926529a9cbc493535ccaf3f118a30cb01fdd7
Author: voidstarstar <voidstarstar@users.noreply.github.com>
Date:   Mon Oct 8 22:09:06 2018 -0400

    Add implementation of ProviderInstallerImpl

 play-services-core/build.gradle                                       | 2 ++
 .../com/google/android/gms/common/security/ProviderInstallerImpl.java | 4 +++-
 2 files changed, 5 insertions(+), 1 deletion(-)
```

I hope this helps!

Detailed debugging process:
*(for others, like myself, that are otherwise easily confused)*

- Made sure I had a baseline:
  - Verified that the last official build that works with BankID is **v0.2.6.13280**
  - Tested all other later official builds and verified that none of them worked.
  - Verified that a local build of *v0.2.6.13280* still worked with BankID.
  - Verified that a local build of *v0.2.7.17455* still did not work with BankID.
- Removed all previous installs of microG Services Core, using `adb shell 'rm /system/priv-app/GmsCore/*'` to remove all contents of `/system/priv-app/GmsCore`.
  - *Note: Since my ROM had no way of granting the spoofing permission (including from the command line), I had to install it this way.*
- Built, signed and zip aligned the apk. Then installed it using `adb push ... /system/priv-app`, in TWRP recovery.
  - Included the commit hash in all my finished apk's, to help make sure I installed the correct file.
- Booted into system. Then made sure to check the app's "Self-Check" tab and the commit listed in the "About" section.
- Did a test involving issuing a BankID certificate via my bank. This required the use of a third-party QR app, which worked well as expected.
- Once I had started the bisection I finished by marking the commit appropriately (good/bad).

**Comment by an0nkyle** [comment] 2019-08-22 02:30
Can you send the zip file for twrp here? :) I'm to lazy

**Comment by jonjonasson** [comment] 2019-08-22 05:30
@AsavarTzeth Thank you for doing this!

Does current master work with the bad commit reverted?

**Comment by AsavarTzeth** [comment] 2019-08-22 19:32
@jonjonasson I will check the first chance I get tomorrow! Its been a busy day.

@an0nkyle What zip file? A zip archive containing the last working apk I built? I don't see the point, since it is hardly much newer than **v0.2.6.13280**. I would personally like to spend my time fixing the issue instead. Hopefully it won't take long!

**Comment by AsavarTzeth** [comment] 2019-08-23 16:35
Reverting the bad commit proved complicated. There was a big conflict to resolve which I did not feel at all comfortable with and any changes I made would likely affects other components.

Luckily I managed to do better!

**Comment by jonjonasson** [comment] 2019-08-23 16:43
@AsavarTzeth Fantastic! Nice find! Big thanks for putting in the time and effort!

**Comment by vildevilde** [comment] 2019-08-23 17:51
@AsavarTzeth I'd like to thank you for your effort, and also all others who helped and tried to help.

But, Excuse me for not knowing, but what happens now? is there a new GmsCore that are working with BankId or will it take some time?

**Comment by chris42** [comment] 2019-08-23 18:07
To have it in the official microg, Marvin will need to review the pull request, accept it and then create a new release. Then it will be regularly available.

If you can't wait for that you can compile the current version with the fix and use it (or ask someone to do that for you). Installing self-compiled versions is easy, but not straight forward.

**Comment by vildevilde** [comment] 2019-08-23 18:17
> To have it in the official microg, Marvin will need to review the pull request, accept it and then create a new release. Then it will be regularly available.
> 
> If you can't wait for that you can compile the current version with the fix and use it (or ask someone to do that for you). Installing self-compiled versions is easy, but not straight forward.

Thank you for a quick and informative answer, I can wait, I just wanted to know what will happen.

**Comment by AsavarTzeth** [comment] 2019-08-23 18:20
Luckily this is a small change that won't affect anything else. The only possible hold up I could foresee is a minor style error or some best practice I am unaware off.

It is certainly possible, since I am a not at all a good programmer and I basically don't know anything specific to Java.

**Comment by vildevilde** [comment] 2019-08-23 18:28
I'm really glad if this issue now is solved for us all here  Sweden :)

Jag tackar och bugar ;)

**Comment by Truberth** [comment] 2019-09-11 21:45
Hi all, what's the latest news on this? I'm on an S7 and get error 134 on BankID and the general vibe of this thread seems to be an optimistic one. Is it possible to get some guidance as to how I should go about fixing this?

Thanks

T Ruberth

**Comment by eklof** [comment] 2019-09-20 06:57
I'm waiting for this issue to be resolved, and so is all swedish third party ROM users, is there some timeline as to when this can be resolved. A few weeks, month ?

**Comment by AsavarTzeth** [comment] 2019-09-20 10:58
@eklof

> To have it in the official microg, Marvin will need to review the pull request, accept it and then create a new release. Then it will be regularly available.

Like many other community projects it is dependent on free time and unpaid work. Therefore there often are no timelines.

The only thing I can tell you is that for the review itself we are likely talking minutes. If the reviewer has a question or requests a change it could take hours, depending on time zone differences (and again availability of free time).

**Comment by AsavarTzeth** [comment] 2019-09-20 11:17
@mar-v-in I understand your time is limited but could you please just do a quick review of this #931? It is a small 2 line fix that would make all Swedish users very happy.

**Comment by osilvab** [comment] 2019-09-27 19:20
Hi, im arriving late to the party. I just installed LOS+microg in my device. 
as I understand if I want bankid to work then i should install an older version of gmscore. right?
how do I install that? I couldnt find any system/priv-app folder. Neither couldnt see the app installed in f-droid to chose older versions

thanks for help!

**Closed** 2019-09-27 22:41 UTC

**Comment by monperrus** [comment] 2019-09-28 05:03
>  as I understand if I want bankid to work then i should install an older version of gmscore. right?

yes, by downloading it from https://github.com/microg/android_packages_apps_GmsCore/releases/

**Comment by eklof** [comment] 2019-09-28 06:05
I tried, but it just fails with "App not installed"


‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by osilvab** [comment] 2019-09-28 08:12
Same for me I downloaded it. It didnt install.

I tried adding the file to /data/app-private but the rom got corrupted and had to format and install again.

**Comment by vildevilde** [comment] 2019-09-28 14:20
As I understand the work to get the fix in to the app is on the way. 

Anyway, as I wrote before my "fix" to get I get around the problem in the mean time by just disable GMSCore in the settings. That make a message in BankId come up that it will not work without Google play service, but just ignore that, tap outside the message  square and BankId will work. Maybe this will affect other apps I don't use very much apps.

**Comment by osilvab** [comment] 2019-09-28 18:30
Thanks @vildevilde. It worked perfectly doing that.

**Comment by eklof** [comment] 2019-09-28 19:09
Hm, How do I find this setting i /e/ ? Di I disable "Google device registration"?


‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by churchthecat** [comment] 2019-09-28 20:41
This thread is closed,  the fix is merged and next update will work. read previous comments, all your questions are answered there.
