### ISSUE TITLE
Unable to start services "gms.appinvite.service.START" & "gms.measurement.START"

### ISSUE THREAD

**Issue by pihug12** [microg/android_packages_apps_GmsCore#404] opened 2017-07-23 11:47 UTC
I can't use the [Molotov](https://apkpure.com/molotov-tv-en-direct-et-en-replay/tv.molotov.app) app on my CM13 device with microG 0.2.4-103.

Two services can't seem to start:

> W/ActivityManager(  439): Unable to start service Intent { act=com.google.android.gms.appinvite.service.START pkg=com.google.android.gms } U=0: not found
> W/ActivityManager(  439): Unbind failed: could not find connection for android.os.BinderProxy@1edfb07
> E/GmsClient(28212): unable to connect to service: com.google.android.gms.appinvite.service.START on com.google.android.gms
> W/ActivityManager(  439): Unable to start service Intent { act=com.google.android.gms.measurement.START pkg=com.google.android.gms } U=0: not found
> W/ActivityManager(  439): Unbind failed: could not find connection for android.os.BinderProxy@33a3434
> E/GmsClient(28212): unable to connect to service: com.google.android.gms.measurement.START on com.google.android.gms

Full logcat: https://gist.github.com/pihug12/dd00400c25a44a731a60646270197f9c

**Comment by dolohow** [comment] 2017-08-11 10:33
I have exactly the same problem using `Splitwise`.  When opening app it says, can't connect to google play services and when you want to log in through Google account, same story.

Logcat is almost identical, but I think the issue is really easy to reproduce.

**Comment by drrossum** [comment] 2017-08-18 14:47
I see the same issue raised by com.whatsapp:
`08-18 16:30:47.776  2570 31563 E GmsClient: unable to connect to service: com.google.android.gms.measurement.START on com.google.android.gms
08-18 16:30:47.780  2570  2570 W FA      : Service connection failed: ConnectionResult{statusCode=API_UNAVAILABLE, resolution=null, message=null}
08-18 16:31:47.747  2570 31614 W FA      : Tasks have been queued for a long time
`
The result is that push messages are not coming in

**Comment by ale5000-git** [comment] 2017-08-31 10:07
@mar-v-in: com.google.android.gms.measurement.START is used by a lot of apps and sometime the app also retry indefinitely when it fail, ref: #344

An infinite retry won't be good for battery I think.

**Comment by maxammann** [comment] 2017-11-12 12:58
Same problem, whatsapp is draining my battery.

**Comment by Freeedim** [comment] 2017-12-31 11:15
My S7 with LineageOS 14.1 and microg (and Xposed on Magisk for signature spoofing) is not able to connect to Internet through cell network (no problem through wifi), could it be related?

Note: everything else works fine (except for the known issues described on this website) and the self-check page has all the boxes checked.

**Comment by ale5000-git** [comment] 2019-01-03 22:08
It should be fixed in the latest version, have you tried?

**Comment by maxammann** [comment] 2019-01-07 13:17
No longer using WhatsApp, but I do not have Issues with Push Notification atm.

**Comment by ale5000-git** [comment] 2019-01-08 16:46
Since the problem no longer happens in the latest version could you please close the ticket?

**Closed** 2019-01-25 19:45 UTC
