### ISSUE TITLE
car2go App won't run unless you update Google Play Services

### ISSUE THREAD

**Issue by deesnook** [microg/android_packages_apps_GmsCore#590] opened 2018-08-06 21:02 UTC
I run LineageOS 15.1 for microG on a OnePlus 3T without GApps. So far, the car2go app (car sharing app that accesses maps) has worked fine. Since an update to v3.23.4, there is an error prompt that requires me to update to a new version of Google Play Services.

I guess this is a common problem with quite a few apps.

LineageOS: v15.1-20180821-microG-oneplus3
microG: v0.2.4-111-gf1cdb48
car2go: v3.24.0

**Comment by x86dev** [comment] 2018-08-12 09:12
+1 here -- seeing this with a lot of apps currently. Is there any reason why the version number can't be at least set manually in the microg settings?

**Comment by cRaZy-bisCuiT** [comment] 2018-08-13 10:51
Quite a lof gapps have this problem, yes. In another #592 would fix this problem and in #511 they say it's not possible to override the number manually without re-compiling. I have no clue why this should be the case.

In a while no gapps will work anymore and the problem gets pointless.

**Comment by x86dev** [comment] 2018-08-13 14:44
Yes, I've read #511 and (still) don' t get why this isn't already there ... it's now only a matter of time until microg will become useless.

**Comment by xenithorb** [comment] 2018-08-13 15:07
Are apps that look for particular versions comparing in a "greater than" way? Can the version support of microg be bumped wildly high such that a particular release of microg could last indefinitely and fool these apps?

**Comment by cRaZy-bisCuiT** [comment] 2018-08-14 07:05
The problem is that we have only one person merging pull requests at the moment. Like this the project will get some problems in the future if things break and no one has the possibility to merge fixes asap.

**Comment by mar-v-in** [comment] 2018-08-28 13:47
Fixed in v0.2.5.12879 / 4040e3df85db5dd59ed3028978a33eb92d7f4e46.

**Closed by mar-v-in** 2018-08-28 13:47 UTC
