### ISSUE TITLE
Google Play Console cannot log in (perhaps Extended Access?)

### ISSUE THREAD

**Issue by oldosfan** [microg/android_packages_apps_GmsCore#817] opened 2019-06-05 13:14 UTC
No stack trace is printed however, as it seems Proguard is stripping all log functions

**Comment by Nanolx** [comment] 2019-06-05 18:59
Duplicate of #810 #790 

With the latest commits you can login, though I don't have a Google Developer Account to test anything beyond logging in (obviously I can log in, but get "Not a developer Account" message).

**Closed** 2019-06-06 00:39 UTC
