### ISSUE TITLE
Google Chrome Keeps Crashing With Latest MicroG, Works Fine on v0.2.7.17455

### ISSUE THREAD

**Issue by timeakesmarky** [microg/android_packages_apps_GmsCore#919] opened 2019-08-08 04:03 UTC
I keep getting these crash files when google chrome crashes:
[exp_det_cert_pin_failure@1565236335295.txt.gz](https://github.com/microg/android_packages_apps_GmsCore/files/3479770/exp_det_cert_pin_failure%401565236335295.txt.gz)
[data_app_crash@1565236569031.txt](https://github.com/microg/android_packages_apps_GmsCore/files/3479771/data_app_crash%401565236569031.txt)

**Comment by Nanolx** [comment] 2019-08-10 12:59
Duplicate of #860 

find a nightly build with the fix included there.

**Closed** 2019-08-10 16:20 UTC
