### ISSUE TITLE
Put app into temporary whitelist when high priority gcm received [$5]

### ISSUE THREAD

**Issue by ccaapton** [microg/android_packages_apps_GmsCore#338] opened 2017-03-05 20:12 UTC
On android M and above and google's implementation, apps will be woken up and put into temporary whitelist by gcm priority message. This is done by addPowerSaveTempWhitelistApp() in IDeviceIdleController.aidl. But in microG there is no such setting, so it leads to some delay in notification. I've experience 30 minutes delay in whatsapp message even microG received from google server on time .

The relevant code is here:
https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/os/IDeviceIdleController.aidl
https://android.googlesource.com/platform/frameworks/base/+/master/services/core/java/com/android/server/DeviceIdleController.java
https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/content/Context.java#3367
https://android.googlesource.com/platform/frameworks/base/+/master/core/res/AndroidManifest.xml#2722

Hope microG could also do this.

**Comment by EinsteinXXL** [comment] 2017-06-20 13:39
I offer 75$!!

**Comment by ale5000-git** [comment] 2017-06-20 13:42
@EinsteinXXL: You haven't put the bounty correctly.
It can be offered [here](https://www.bountysource.com/issues/42703986-put-app-into-temporary-whitelist-when-high-priority-gcm-received).

**Comment by Catfriend1** [comment] 2018-01-27 11:05
Is this issue caused by the missing firebase support in microg ? 
FCM xda source https://www.xda-developers.com/broken-push-notifications-fix/

**Comment by ale5000-git** [comment] 2018-01-27 12:27
@Catfriend1: I think it is unrelated, this one is related to Doze / energy saving.

**Comment by Catfriend1** [comment] 2018-01-27 19:53
Thanks for answering. Even if this might not be the right thread to discuss it, can you give me a hint why my whatsapp messages never trigger a notification in android? I just get those text messages when I open the app to the foreground. Looked almost everywhere, permissions should be ok, it was okay on cyanogenmod 6 + microg gms, but no longer since i am on lineage 14.1 + microg gms - no matter which release date of the custom rom. I am currently on LG H815 with Lineage 14.1 (2017-11-07) Android 7.1.2 and manually applied sigspoof patch + microg gms most recent version. I see in the microg app, whatsapp correctly registered for GCM service and does get GCM messages. But it does get them silently and not show any notification a message has arrived. When I click-open whatsapp, I see for about half a second no new message and then the message flys in. I have notifications enabled in whatsapp settings (checked twice and more). What is going on with this? A whatsapp or microg problem?

**Comment by ccaapton** [comment] 2018-01-28 00:43
@Catfriend1 This is definitely because of this issue. 

I have a working commit to solve this, but it uses private api, and needs microg to be priv-app. In addition a seperate file need to be placed into /system/etc/permissions. So it is unlikely to be accepted by microg

**Comment by ale5000-git** [comment] 2018-01-28 01:28
@ccaapton: Could you please explain it in details your fix and post a link?

**Comment by Catfriend1** [comment] 2018-01-28 09:22
@ccaapton can the private api (what is it?) be put separately on the system partition or as an extension module like droidguard helper? My microg is installed to priv-app. Modifiying system/permissions... Which one? Thanks for helping me :)

**Comment by ale5000-git** [comment] 2018-01-29 09:57
@ccaapton

I just found your `https://github.com/microg/android_packages_apps_GmsCore/compare/master...ccaapton:master`

What about the file in /system/etc/permissions ?

**Comment by ccaapton** [comment] 2018-01-29 12:06
@ale5000-git My code is out of sync with the github one, and not easy to get sync. There are more parts need to be done, including adding a new aidl and manually convert to java stub. I have not touch the code for quite long time, and got a bit rusty.

For the xml in /etc/permissions, you need to grep "com.android.providers.download", and give microg same the treatment as that package.

If you know how to code, perhaps we can chat in email so you could help me to get this upstream.

**Comment by Catfriend1** [comment] 2018-01-29 19:21
fyi, MicroG did not make much update releases since 2017-03 when you last changed your fork.

**Comment by ale5000-git** [comment] 2018-06-20 01:11
@ccaapton: I have made it compile successfully as Travis CI reported but I haven't tested it.

**Comment by ccaapton** [comment] 2018-06-21 13:29
@ale5000-git Your commit 67de6f4 is basically what I previously did. It should be able to put other apps into temporary whitelist, together with a new permission file /system/etc/permissions/microg.xml:
```
<permissions>
  <allow-in-power-save package="com.google.android.gms" />
</permissions>
```
(There is also equivalent /system/etc/sysconfig/microg-a5k.xml with `<config/>` syntax)

You can use `adb shell dumpsys deviceidle whitelist` and `adb shell dumpsys deviceidle tempwhitelist` to test&verify.

In the AIDL file `IDeviceIdleController.aidl`, the method `addPowerSaveTempWhitelistApp` need a `userID` argument, it will usually be zero for normal apps, but none-zero for managed-profile apps or apps installed by non-primary users. I did not know how to get the userID of the target app, so I always use 0, but it is problematic in multi-user or managed-profile scenario. In fact this is the major reason why I did not push my work upstream. @ale5000-git  @mar-v-in Do you know how to solve this?

**Comment by nicman23** [comment] 2019-01-05 17:35
Any progress on this?

**Comment by voidstarstar** [comment] 2019-02-28 14:01
> I did not know how to get the userID of the target app, so I always use 0, but it is problematic in multi-user or managed-profile scenario.

Just a guess, but is [`msg.device_user_id`](https://github.com/microg/android_packages_apps_GmsCore/blob/1e444dc4aaae56c381e3e6621f8c0d188963ca03/play-services-core/src/main/protos-java/org/microg/gms/gcm/mcs/DataMessageStanza.java#L141) what is needed?

Also, related to #650

**Comment by voidstarstar** [comment] 2019-03-17 00:39
@ccaapton @ale5000-git 

I think I may have fixed a bug that caused `mDeviceIdleController` to remain null.  The `Context.DEVICE_IDLE_CONTROLLER` field is hidden and wasn't properly being passed.

Using the command `adb shell dumpsys deviceidle`, an app that receives a push notification now appears in the temp whitelist for 10 seconds!  The [branch is available here](https://github.com/voidstarstar/android_packages_apps_GmsCore/tree/temporary_whitelist).  I also have a [compiled binary here](https://github.com/voidstarstar/android_packages_apps_GmsCore/releases/tag/temporary_whitelist) for testing purposes.  (These will be deleted once merged upstream.)

> In the AIDL file IDeviceIdleController.aidl, the method addPowerSaveTempWhitelistApp need a userID argument, it will usually be zero for normal apps, but none-zero for managed-profile apps or apps installed by non-primary users. I did not know how to get the userID of the target app, so I always use 0, but it is problematic in multi-user or managed-profile scenario.

Does the `userID` need to be the UID of the receiving app or the UID of microG?  I tried modifying the code to use the UID of the receiving app, but in the logcat the `ActivityManager` said it expected a 0.  I'm not running in a multi-user or managed profile setting, so I didn't test those configurations, but using 0 seemed to work for me (once I fixed the bug mentioned above).

Hopefully someone can test this out to confirm it works.  Testing in a multi-user and managed profile environment would be great too.  I'd love to see this get merged in before the next microG release since this likely affects nearly all users.  If this looks good, let me know if you'd like me to open a PR.

**Comment by voidstarstar** [comment] 2019-03-18 17:55
I think I solved the multi-user problem too.  It required some ugly reflection, due to more hidden APIs, but it seems to work.  I am unable to test this for managed profiles, however.  Since this seems to me like it's now working, I've opened a PR #732.

**Closed** 2019-04-21 14:39 UTC
Labels: bounty

**Comment by ale5000-git** [comment] 2019-06-02 12:27
@ccaapton
@voidstarstar

One of you should claim the bounty [here](https://www.bountysource.com/issues/42703986-put-app-into-temporary-whitelist-when-high-priority-gcm-received).

**Comment by voidstarstar** [comment] 2019-06-02 14:59
@ale5000-git It looks like you were involved in this one too.

I just did some general refactoring and code maintenance for the most part.  I fixed a couple bugs and figured out how to get the userID, but this isn't really a significant contribution.  One of you two should claim it. :tada:

**Comment by ale5000-git** [comment] 2019-06-02 15:21
My contribution was minimal in this issue, maybe it should be left to @ccaapton that was the original creator.

**Comment by ale5000-git** [comment] 2019-06-13 17:27
@ccaapton
