### ISSUE TITLE
Unable to sign into Gmail, other Gapps

### ISSUE THREAD

**Issue by mwsduelle** [microg/android_packages_apps_GmsCore#533] opened 2018-04-22 03:22 UTC
I have already added my Google account under Settings>Account, When I open Gmail, it asks me for my email address (instead of just using the account that's already there) and when I enter it I get the message "this account already exists on this device". There is no way to choose the account, though; only a text field to enter the email address. Chrome/Chromium has the same issue. Maps signs me in automatically, though.

Using the latest version (just installed LOS for MicroG today).

**Comment by firstamendment** [comment] 2018-04-22 14:58
Try signing out your account and signing in via gmail.

**Comment by Tom4tot** [comment] 2018-04-25 20:53
https://forum.xda-developers.com/showpost.php?p=76314517&postcount=841

I have the same issue. I've tried many different things and it doesn't work. If i remove my account and sign-in through gmail, after the google account, gmail is just going to go back to the default page, asking again for a google account (or something else).

Partial fix : use gmail as IMAP. It's not as convenient but it's better than nothing.

**Comment by e00E** [comment] 2018-06-11 19:29
I can confirm this issue on the latest Lineage OS for MicroG.

**Comment by jimbo1qaz** [comment] 2018-09-29 03:03
microG 0.2.6.13280 from either lineage microg, or f-droid microg repo.

```
2018-09-28 20:00:28.283 923-3877/system_process I/ActivityManager: START u0 {cmp=com.google.android.gm/.welcome.SetupAddressesActivity (has extras)} from uid 10093 on display 0
2018-09-28 20:00:28.485 30939-30939/com.google.android.gms D/GmsFeedbackSvc: onBind: Intent { act=com.google.android.gms.feedback.internal.IFeedbackService pkg=com.google.android.gms }
2018-09-28 20:00:28.490 30939-30939/com.google.android.gms D/GmsPeopleSvc: onBind: Intent { act=com.google.android.gms.people.service.START pkg=com.google.android.gms }
2018-09-28 20:00:28.498 942-994/com.google.android.gm W/Gmail: Gmail:No valid account details in bundle: empty username, email address and/or host
2018-09-28 20:00:28.499 942-942/com.google.android.gm W/Gmail: Gmail:For b/73513912, load account content://com.google.android.gm2.accountcache from AccountLoadCallbacks. Is account valid result: 0.
2018-09-28 20:00:28.511 942-942/com.google.android.gm W/Gmail: Gmail:For b/73513912, load account content://com.android.gmail.ui/account.-2137146394 from MailAppProvider. Is account valid result: 1.
2018-09-28 20:00:28.512 942-942/com.google.android.gm W/Gmail: Gmail:For b/73513912, load account content://com.google.android.gm.email.provider/account.-437561172?suppress_combined%3Dtrue from MailAppProvider. Is account valid result: 1.
2018-09-28 20:00:28.539 30939-30952/com.google.android.gms D/SafeParcel: Unknown field num 10 in com.google.android.gms.common.internal.GetServiceRequest, skipping.
2018-09-28 20:00:28.540 30939-30952/com.google.android.gms D/GmsPeopleSvc: bound by: GetServiceRequest{serviceId=PEOPLE, gmsVersion=12525000, packageName='com.google.android.gm', extras=Bundle[{support_new_image_callback=true, social_client_application_id=135, real_client_package_name=com.google.android.gm}]}
2018-09-28 20:00:28.544 30939-30951/com.google.android.gms D/SafeParcel: Unknown field num 10 in com.google.android.gms.common.internal.GetServiceRequest, skipping.
2018-09-28 20:00:28.545 30939-30951/com.google.android.gms D/GmsFeedbackSvc: bound by: GetServiceRequest{serviceId=FEEDBACK, gmsVersion=12525000, packageName='com.google.android.gm', extras=Bundle[{}]}
2018-09-28 20:00:28.596 923-970/system_process I/ActivityManager: Displayed com.google.android.gm/.welcome.SetupAddressesActivity: +299ms
```

This line looks telling:

> Gmail:No valid account details in bundle: empty username, email address and/or host

**Comment by jimbo1qaz** [comment] 2018-09-29 08:16
Compare with a logcat of me logging into Island Gmail on a Google Play Services phone:

No accounts present, loading Gmail screen:
```
    --------- beginning of main
2018-09-29 00:46:59.457 32112-32112/? W/Gmail: Gmail:For b/73513912, load account content://com.google.android.gm2.accountcache from AccountLoadCallbacks. Is account valid result: 0.
2018-09-29 00:46:59.459 32112-32142/? W/Gmail: Gmail:No valid account details in bundle: empty username, email address and/or host
```

After adding account, Gmail returns to "add account" screen takes several seconds to list my Gmail:
```
timestamp: clicked "accept ToS"
2018-09-29 00:48:31.093 2482-12333/? I/ActivityManager: START u10 {flg=0x2000000 cmp=com.google.android.gms/.auth.uiflows.addaccount.AddAccountActivity (has extras)} from uid 1010035 on display 0

timestamp: I'm guessing "return to gmail app"
2018-09-29 00:48:34.291 32112-32112/? W/Gmail: Gmail:For b/73513912, load account content://com.google.android.gm2.accountcache from AccountLoadCallbacks. Is account valid result: 0.

timestamp: I'm guessing "account shows up in gmail app"
2018-09-29 00:48:38.386 32112-32112/? W/Gmail: Gmail:For b/73513912, load account content://com.google.android.gm2.accountcache from AccountLoadCallbacks. Is account valid result: 0.
```

Is Gmail similar to https://android.googlesource.com/platform/packages/apps/UnifiedEmail/+/master/src/com/android/mail/ui/AccountLoadCallbacks.java ?

--------

reopening gmail app with existing account:

>2018-09-29 00:56:56.331 2086-2086/? W/Gmail: Gmail:For b/73513912, load account content://com.google.android.gm2.accountcache from AccountLoadCallbacks. Is account valid result: 0.
2018-09-29 00:56:56.332 2086-2119/? W/Gmail: Gmail:No valid account details in bundle: empty username, email address and/or host

https://developer.android.com/reference/android/app/LoaderManager.LoaderCallbacks

**Comment by jimbo1qaz** [comment] 2018-09-29 10:46
Weird, I removed `pm install` signature verification via Lucky Patcher, cleared microG data, installed from Git, and "TAKE ME TO GMAIL" works.

Then I cleared microG and Gmail, reverted microG to factory, and it *still* works.

**Comment by voidstarstar** [comment] 2018-10-11 16:51
@jimbo1qaz Have you tried simply enabling the Contacts permission for the Gmail app?  https://github.com/microg/android_packages_apps_GmsCore/issues/467#issuecomment-355568469

It seems odd that it does not request the permission and instead requires manually enabling it, but this seemed to solve the issue for me.

**Comment by jimbo1qaz** [comment] 2018-10-12 09:35
Contacts permission is enabled. I have not tried disabling it, wiping Lucky Patcher's ART cache mods, and seeing if Gmail breaks.

**Comment by je-vv** [comment] 2018-10-17 04:12
BTW, with "ineage-15.1-20181016-microG-santoni" I'm experiencing the same, and I added the contacts permissions, and still got in the loop of gmail requesting for a new account, and complaining the one provided already exists, if providing it so...

**Comment by TheInitializer** [comment] 2018-11-08 04:36
I have the same issue in Gmail, AOSP Contacts, AOSP Calendar and Google Contacts though YouTube and Google Photos work fine.

**Comment by breversa** [comment] 2019-04-02 07:27
The issue persists with MicroG 0.2.6.1580-dirty-227 from NanoDroid (https://nanolx.org/nanolx/nanodroid)

**Comment by ale5000-git** [comment] 2019-07-15 07:03
Please update to [this build](https://microg.org/dl/GmsCore-v0.2.8.17785-4-06c8b76.apk) and retry.

**Comment by breversa** [comment] 2019-07-15 08:36
Sorry, I forgot to reply that Gmail has been working fine for me since 0.2.7 already. :-)

**Comment by ale5000-git** [comment] 2019-07-15 10:17
Fixed by this: https://github.com/microg/android_packages_apps_GmsCore/commit/30ed2720a0ecd3067fe760e801ecbdbe1b5ff5be

**Closed by ale5000-git** 2019-07-15 10:17 UTC
Labels: 👥 Google Accounts

**Comment by je-vv** [comment] 2019-07-16 00:27
Using 0.2.8 already and trying to use gmail always fail indicating the account already exists in the device.  Actually using Lineage for MicroG...

**Comment by ale5000-git** [comment] 2019-07-16 06:55
@je-vv: Please update to [this build](https://microg.org/dl/GmsCore-v0.2.8.17785-4-06c8b76.apk) and retry.

It contains fixes needed for new Android versions (it is more recent then the plain 0.2.8).

**Comment by jwalker9715** [comment] 2019-08-06 17:29
@ale5000-git
I'm getting this non ending loading when trying to restore my backup for Daylio from Google drive. 
I'm using latest version of microg giving permission to daylio and gdrive (which I wasn't sure if needed on phone so I installed). Any suggestions?
I don't have a problem with other gapps or better say I fixed calendar with throwing calendar sync into system folder with permissions.

**Comment by ale5000-git** [comment] 2022-01-26 13:30
@jwalker9715
Please try microG GmsCore 0.2.23.214816 and if it still doesn't work please open a separate issue.
