### ISSUE TITLE
Cant log - just a sec... (Solved)

### ISSUE THREAD

**Issue by CBLuiSo** [microg/android_packages_apps_GmsCore#387] opened 2017-06-07 01:46 UTC
Im running Miui 8.3 (Marshmallow) all gapps uninstalled following the guide, Signature Spoofing enabled with xposed, all apps are correctly installed on system/priv-app but i cant login, it gets stucked on Just a sec.... any idea?

Rom changed to Official Lineage OS 14.1 (cancro), MIUI even with global rom or EU rom has a lot of blotware from google, even uninstallating all of google applications, I did not make MicroG to work, so **this post is related to Lineage OS rom not to MIUI rom**

**Comment by teoman002** [comment] 2017-06-07 05:30
same issue here!

**Comment by JonnyTech** [comment] 2017-06-07 07:35
Which version of microg?

**Comment by CBLuiSo** [comment] 2017-06-07 10:43
Last one from this page https://microg.org/download.html

**Comment by ale5000-git** [comment] 2017-06-07 11:26
@CBLuiSo: It son't mean anything, since one can think to have get the latest version but usually it isn't.

See the version inside the phone.

**Comment by teoman002** [comment] 2017-06-07 11:34
I have microG 0.2.4 installed.
Note 4, Emotion-AOSP-ROM-r23 , Android 6.0.1

**Comment by ale5000-git** [comment] 2017-06-07 11:38
@teoman002: The problem is usually that if one install microG from F-Droid also if he/she select manually the latest preview build (which is updated and working) usually it get the latest release build (which is quite old).

If you have just "microG 0.2.4", you are using the latest release build which is quite old.

**Comment by CBLuiSo** [comment] 2017-06-07 11:40
@ale5000-git so where we have to download the apks to be sure? thanks in advance

**Comment by ale5000-git** [comment] 2017-06-07 11:43
Here: https://microg.org/download.html

But you have to select the drop-down menu and manually select the latest preview version.

**Comment by CBLuiSo** [comment] 2017-06-07 12:12
@ale5000-git i installed official lineage os 14.1 for my mi4, following this guide http://www.gabsoftware.com/tips/how-to-use-microg-on-lineageos-or-cyanogenmod-without-xposed/ i enabled succesfull the signature spoofing and now MicroG is working, i have one question more, the sync is disabled and i cant enabled it, is this correct?

**Comment by ale5000-git** [comment] 2017-06-07 12:25
"Sync" is generic, microG doesn't include any sync apk but you can install for example the Calendar Sync apk (or others) from Google and use it with microG.

**Comment by CBLuiSo** [comment] 2017-06-07 12:26
@ale5000-git Thanks ale, i will try, one more thing, i noticed that my microg says that "My signature spoofing is not enabled" but all services works fine, is this normal?

**Comment by ale5000-git** [comment] 2017-06-07 12:28
Can you post a screenshot?

**Comment by CBLuiSo** [comment] 2017-06-07 12:30
![screenshot_20170607-142914](https://user-images.githubusercontent.com/29242212/26878459-d923226a-4b8d-11e7-8be8-4964aa10c4bc.png)
![screenshot_20170607-142920](https://user-images.githubusercontent.com/29242212/26878460-d9455358-4b8d-11e7-986d-9fb9af8df445.png)
![screenshot_20170607-142931](https://user-images.githubusercontent.com/29242212/26878461-d951c430-4b8d-11e7-986d-ff3464b67bb3.png)

Here you go

**Comment by CBLuiSo** [comment] 2017-06-07 12:34
I installed Google contact sync, reboot and the phone ask me for permission to enable sync, but still off, no contact sync is done

**Comment by ale5000-git** [comment] 2017-06-07 12:39
There is something wrong with signature spoofing.

Are you sure you have replaced the file correctly after patching?
If yes, try to clean the dalvik/ART cache from the recovery.

**Comment by CBLuiSo** [comment] 2017-06-07 12:47
I think so, maybe i have to add extra permissions to framework.jar? or to gsmcore and gsf

**Comment by ale5000-git** [comment] 2017-06-07 12:56
framework.jar doesn't need anything.

You could try to uninstall and reinstall microG GmsCore (but you will lost GCM registration and you may have to reinstall also the apps that use it).

**Comment by CBLuiSo** [comment] 2017-06-07 13:06
@ale5000-git now is working, i patched framework again but in this case i pull the .jar manually with root explorer, all perfect, now im trying to get google contact sync working, i added the google account again but sync still off

**Comment by JonnyTech** [comment] 2017-06-07 13:09
https://github.com/microg/android_packages_apps_GmsCore/issues/222#issuecomment-261253801

**Comment by CBLuiSo** [comment] 2017-06-07 14:13
@JonnyTech thanks for the reply, but i just installed googlesyncadapter.apk, give it full permissions and then i add the google account through my calendar app and now both syncs are working good
![screenshot_20170607-161223](https://user-images.githubusercontent.com/29242212/26882973-3414ddb8-4b9c-11e7-88e9-475539eb52d6.png)
![screenshot_20170607-161233](https://user-images.githubusercontent.com/29242212/26882974-34352730-4b9c-11e7-92ab-828fbff4f913.png)

**Comment by teoman002** [comment] 2017-06-07 15:18
Problem solved! Thank you!
I installed the last gmscore_debug.apk in system\app folder with 644 permissions.
Received last version from here: http://files.brnmod.rocks/apps/GmsCore/Latest/

**Comment by ale5000-git** [comment] 2017-06-07 15:34
@teoman002: It is an old version.

The latest version is here: https://microg.org/download.html
You have to use the drop-down menu and select manually the last preview build.

**Comment by CBLuiSo** [comment] 2017-06-07 17:59
Thanks for all the support @ale5000-git btw, MicroG is still in development? will be future updates?

I really hate Google lol

**Comment by JonnyTech** [comment] 2017-06-07 19:02
> I really hate Google lol

So do not use googlesyncadapter and calendarsync ;)

Yes, **mar-v-in** is still improving microg all the time, when he has the time.

**Comment by CBLuiSo** [comment] 2017-06-07 19:10
@JonnyTech Thats not the problem, the problem is the constant location wakelocks from google even with out user authorization, the battery drains due to useless processes that the user will never use and a long long etc

**Comment by ale5000-git** [comment] 2017-06-07 22:28
It is still in development but he has his life also so it may take time :)

**Comment by ale5000-git** [comment] 2017-06-10 11:18
@CBLuiSo: Hi, there is no need to put "Solved" in the title, just close it if it is solved.

**Closed** 2017-06-10 11:29 UTC
