### ISSUE TITLE
Unable to login to Google Account

### ISSUE THREAD

**Issue by AlternativeZero** [microg/android_packages_apps_GmsCore#770] opened 2019-04-25 03:37 UTC
I'm not sure why but I'm unable to login to a Google account, I attached my logcat to see if this problem can be fixed.

[logcat.txt](https://github.com/microg/android_packages_apps_GmsCore/files/3114965/logcat.txt)

**Comment by ImAnnoying2** [comment] 2019-04-26 08:26
Duplicate of #756

**Comment by MrDodojo** [comment] 2019-04-26 21:12
Might be because the latest chrome breaks the login in microG as it system app replaces the built in webview? (it's like that for the Vanced Microg)

Would one of you like to try this https://www.reddit.com/r/Vanced/comments/bhkq6q/are_you_having_issues_getting_past_login/
Which has been proven effective by multiple people.(Again, YouTube Vanced MicroG)

**Comment by AlternativeZero** [comment] 2019-04-26 22:04
@MrDodojo  I don't have Chrome installed, I do have [Bromite WebView](https://github.com/bromite/bromite) But I'm not sure if that is the cause of the problem.

**Comment by Nanolx** [comment] 2019-05-02 10:06
Yes it's very likely an issue with Bromite/WebView/Chromium, several users reported rolling back to v72 fixed the issue, so they could re-update to v74 afterwards.

**Comment by benyaminl** [comment] 2019-05-05 12:03
> Yes it's very likely an issue with Bromite/WebView/Chromium, several users reported rolling back to v72 fixed the issue, so they could re-update to v74 afterwards.

Does version 73 also having the problem? Thanks

**Comment by Nanolx** [comment] 2019-05-05 12:31
No, v73 us fine, too.

Am 5. Mai 2019 14:03:41 MESZ schrieb Benyamin Limanto <notifications@github.com>:
>> Yes it's very likely an issue with Bromite/WebView/Chromium, several
>users reported rolling back to v72 fixed the issue, so they could
>re-update to v74 afterwards.
>
>Does version 73 also having the problem? Thanks
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/microg/android_packages_apps_GmsCore/issues/770#issuecomment-489419996

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by benyaminl** [comment] 2019-05-06 01:23
> No, v73 us fine, too. Am 5. Mai 2019 14:03:41 MESZ schrieb Benyamin Limanto <notifications@github.com>:
> […](#)
> > Yes it's very likely an issue with Bromite/WebView/Chromium, several users reported rolling back to v72 fixed the issue, so they could re-update to v74 afterwards. Does version 73 also having the problem? Thanks -- You are receiving this because you commented. Reply to this email directly or view it on GitHub: [#770 (comment)](https://github.com/microg/android_packages_apps_GmsCore/issues/770#issuecomment-489419996)
> -- Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

I want to try bromite web view.

**Comment by Nanolx** [comment] 2019-05-09 15:42
I may add to this, that it's indded not just Bromite/Bromite WebView, but confirmed (by users) that it's also Google WebView or when using Chrome/Chromium as WebView provider.

@mar-v-in this should be marked as critical issue before the next release.

GmsAuthenticator believes the Token has expired, a bit more details extracted from logcat (XXX-out tokens, IDs and Account):

```
05-09 16:31:33.468  7132  7165 D GmsAuthenticator: getAuthToken: Account {name=XXXXXXXXXXXXXXXX@gmail.com, type=com.google}, oauth2:https://www.googleapis.com/auth/googleplay, Bundle[{androidPackageName=com.android.vending, callerPid=16276, callerUid=10123, notifyOnAuthFailure=true}]
05-09 16:31:33.480  7132  7165 D GmsAuthManager: peekAuthToken: com.android.vending:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX:oauth2:https://www.googleapis.com/auth/googleplay
05-09 16:31:33.481  7132  7165 D GmsAuthenticator: getAuthToken: XXXX.XXXXXXX-XXXXXXXXXXXXXXXXXX-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX-XXXXXXX_XXX_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX-XXXXXXX_X_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX-XXXXXXXXXXXXXXXXXX_XXXXXXXXXXXXXXXXXXXXXXXXXXX-X_XXXXXXXXXXXXXXXXXXXXXXXX
05-09 17:17:15.019  7132  7132 D GmsAuthLoginBrowser: pageFinished: https://accounts.google.com/
05-09 17:17:15.265  7132 19431 D GmsAuthLoginBrowser: Terms of service accepted. (who cares?)
05-09 17:17:16.027  7132 19431 D GmsAuthLoginBrowser: JSBridge: showView
05-09 17:17:16.389  7132  7132 D GmsAuthLoginBrowser: pageFinished: https://accounts.google.com/EmbeddedSetup/identifier?source=android&xoauth_display_name=Android%20Device&lang=de&cc=de&langCountry=de_de&hl=de-DE&tmpl=new_account&flowName=EmbeddedSetupAndroid
05-09 17:17:42.689  7132 19431 D GmsAuthLoginBrowser: JSBridge: getDroidGuardResult: ["XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"]
05-09 17:17:44.520  7132 19431 D GmsAuthLoginBrowser: JSBridge: showView
05-09 17:17:50.500  7132 19431 D GmsAuthLoginBrowser: JSBridge: getDroidGuardResult: ["XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"]
05-09 17:17:56.339  7132  7132 D GmsAuthLoginBrowser: pageFinished: https://accounts.google.com/
05-09 17:18:41.253  7132  7132 D GmsAuthLoginBrowser: pageFinished: https://accounts.google.com/EmbeddedSetup/signinconsent?source=android&xoauth_display_name=Android%20Device&lang=de&cc=de&langCountry=de_de&hl=de-DE&tmpl=new_account&flowName=EmbeddedSetupAndroid&TL=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX&cid=1

05-09 17:21:38.315  7132 16187 D GmsAuthenticator: getAuthToken: Account {name=XXXXXXXXXXXXXXXX@gmail.com, type=com.google}, oauth2:https://www.googleapis.com/auth/googleplay, Bundle[{androidPackageName=com.android.vending, callerPid=16276, callerUid=10123, notifyOnAuthFailure=true}]
05-09 17:21:38.324  7132 16187 D GmsAuthManager: token present, but expired
05-09 17:21:38.339  7132 16187 D GmsHttpFormClient: -- Request --
05-09 17:21:38.339  7132 16187 D GmsHttpFormClient: accountType=HOSTED_OR_GOOGLE&androidId=XXXXXXXXXXXXXXXX&app=com.android.vending&client_sig=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX&callerPkg=com.google.android.gms&callerSig=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX&device_country=DE&Email=XXXXXXXXXXXXXXXX%40gmail.com&google_play_services_version=1518000&is_called_from_account_manager=1&_opt_is_called_from_account_manager=1&lang=de_DE&operatorCountry=DE&sdk_version=28&service=oauth2%3Ahttps%3A%2F%2Fwww.googleapis.com%2Fauth%2Fgoogleplay&source=android&system_partition=1
05-09 17:21:38.541  7132 16187 W GmsAuthenticator: 
05-09 17:21:38.541  7132 16187 W GmsAuthenticator: java.io.IOException: Error=BadAuthentication
05-09 17:21:38.541  7132 16187 W GmsAuthenticator: 	at org.microg.gms.common.HttpFormClient.request(HttpFormClient.java:90)
05-09 17:21:38.541  7132 16187 W GmsAuthenticator: 	at org.microg.gms.auth.AuthRequest.getResponse(AuthRequest.java:189)
05-09 17:21:38.541  7132 16187 W GmsAuthenticator: 	at org.microg.gms.auth.AuthManager.requestAuth(AuthManager.java:211)
05-09 17:21:38.541  7132 16187 W GmsAuthenticator: 	at org.microg.gms.auth.loginservice.AccountAuthenticator.getAuthToken(AccountAuthenticator.java:96)
05-09 17:21:38.541  7132 16187 W GmsAuthenticator: 	at android.accounts.AbstractAccountAuthenticator$Transport.getAuthToken(AbstractAccountAuthenticator.java:246)
05-09 17:21:38.541  7132 16187 W GmsAuthenticator: 	at android.accounts.IAccountAuthenticator$Stub.onTransact(IAccountAuthenticator.java:114)
05-09 17:21:38.541  7132 16187 W GmsAuthenticator: 	at android.os.Binder.execTransact(Binder.java:731)
```

**Comment by MrDodojo** [comment] 2019-05-09 15:45
> Yes it's very likely an issue with Bromite/WebView/Chromium, several users reported rolling back to v72 fixed the issue, so they could re-update to v74 afterwards.

And with chrome you can just disable chrome/chromium to log in

**Comment by Shadowsteak** [comment] 2019-05-11 21:22
Yeah Chrome 74 is blocking the login of micro g
Please uninstall it and retry it will work.

**Comment by Nanolx** [comment] 2019-05-27 09:07
Fixed with commit 45ee4903f88c36c83b07379b30a07fbb09a4d07a

Successfully tested with Bromite WebView 75.0.3770.53 (current latest release).

**Comment by benyaminl** [comment] 2019-05-27 09:33
> Fixed with commit 45ee490 by mar-v-in
> Successfully tested with Bromite WebView 75.0.3770.53 (current latest release).
> Thanks.

So we need to build the APK by ourself then?

**Comment by Nanolx** [comment] 2019-05-27 10:06
For now, yes, if you're on the official build.

**Comment by ale5000-git** [comment] 2019-06-01 15:16
Bug should be fixed, new version is out (please report if not fixed for you).

**Closed by ale5000-git** 2019-06-01 15:16 UTC
Labels: bug, 👥 Accounts
