### ISSUE TITLE
App "Radio France" crashes at startup

### ISSUE THREAD

**Issue by mishka81** [microg/android_packages_apps_GmsCore#1163] opened 2020-09-09 18:50 UTC
I'm running ResurrectionRemix 5.7.4, e.g AOSP 6.0.1 and the microG Services Core 
0.2.11.202414

App crashes at startup :

> 09-09 20:39:43.770 23735 23735 E AndroidRuntime:        at com.google.android.gms.cast.framework.internal.ICastDynamiteModule$Stub.onTransact(ICastDynamiteModule.java:84)
> 09-09 20:39:43.770 23735 23735 E AndroidRuntime:        at android.os.Binder.transact(Binder.java:387)
> 09-09 20:39:43.770 23735 23735 E AndroidRuntime:        at com.google.android.gms.internal.cast.zzb.zza(com.google.android.gms:play-services-cast@@18.1.0:10)
> 09-09 20:39:43.770 23735 23735 E AndroidRuntime:        at com.google.android.gms.internal.cast.zzaj.zza(com.google.android.gms:play-services-cast-framework@@18.1.0:8)
> 09-09 20:39:43.770 23735 23735 E AndroidRuntime:        at com.google.android.gms.internal.cast.zzae.zza(com.google.android.gms:play-services-cast-framework@@18.1.0:3)
> 09-09 20:39:43.770 23735 23735 E AndroidRuntime:        at com.google.android.gms.cast.framework.CastContext.<init>(com.google.android.gms:play-services-cast-framework@@18.1.0:39)
> 09-09 20:39:43.770 23735 23735 E AndroidRuntime:        at com.google.android.gms.cast.framework.CastContext.getSharedInstance(com.google.android.gms:play-services-cast-framework@@18.1.0:6)
> 09-09 20:39:43.770 23735 23735 E AndroidRuntime:        at com.radiofrance.player.PlayerService.onCreate(PlayerService.java:158)
> 09-09 20:39:43.770 23735 23735 E AndroidRuntime:        at com.radiofrance.radio.radiofrance.android.service.player.EchoesPlayerService.onCreate(EchoesPlayerService.kt:45)
> 09-09 20:39:43.770 23735 23735 E AndroidRuntime:        at android.app.ActivityThread.handleCreateService(ActivityThread.java:2923)
> 09-09 20:39:43.770 23735 23735 E AndroidRuntime:        ... 8 more
> 09-09 20:39:43.770 23735 23735 E AndroidRuntime: Caused by: java.lang.RuntimeException: Overread allowed size end=1012
> 09-09 20:39:43.770 23735 23735 E AndroidRuntime:        at org.microg.safeparcel.SafeParcelUtil.readObject(SafeParcelUtil.java:103)
> 09-09 20:39:43.770 23735 23735 E AndroidRuntime:        at org.microg.safeparcel.SafeParcelUtil.createObject(SafeParcelUtil.java:37)
> 09-09 20:39:43.770 23735 23735 E AndroidRuntime:        ... 20 more

**Comment by ArchangeGabriel** [comment] 2020-09-10 13:32
Duplicate of https://github.com/microg/android_packages_apps_GmsCore/issues/1111

**Comment by ArchangeGabriel** [comment] 2020-10-13 20:09
Fixed with https://github.com/microg/android_packages_apps_GmsCore/commit/dbcf70f99ec36e68a886efef5f4552fe0e0d7e7e.

**Closed** 2020-10-13 20:55 UTC
