### ISSUE TITLE
Cant get uber to work?

### ISSUE THREAD

**Issue by 8bitjoe** [microg/android_packages_apps_GmsCore#364] opened 2017-05-02 02:57 UTC
I recently installed microg version 0.2.4-81-gb1e98ea, but i cant seem to get uber to work?
Here is the logcat of the warnings and errors i get from uber: https://pastebin.com/bza5aqEi

im thinking its a problem with google maps api or something?

**Comment by ale5000-git** [comment] 2017-05-02 11:18
Make sure you have microG Services Framework Proxy installed
and update microG Services Core to 0.2.4-92.

Reinstall uber and retry.

**Comment by 8bitjoe** [comment] 2017-05-02 13:40
Microg Services Framework is indeed installed, i updated microg to latest release and reinstalled uber but it still doesn't work.

**Comment by haidahaha** [comment] 2017-05-15 21:04
update to 0.2.4-92 fixes my problem with Uber

**Comment by alinefr** [comment] 2017-05-29 05:31
Uber is not working for me for a couple of months. Version 3.141.7 works fine. But any attempt to install any newer version makes it crash right when I have to choose my destination.
```
05-29 02:22:51.765 12143 12143 E AndroidRuntime: FATAL EXCEPTION: main
05-29 02:22:51.765 12143 12143 E AndroidRuntime: Process: com.ubercab, PID: 12143
05-29 02:22:51.765 12143 12143 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'void com.google.android.gms.maps.internal.IOnMapLoadedCallback.onMapLoaded()$
 on a null object reference
05-29 02:22:51.765 12143 12143 E AndroidRuntime:        at org.microg.gms.maps.GoogleMapImpl$2.run(GoogleMapImpl.java:549)
05-29 02:22:51.765 12143 12143 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:751)
05-29 02:22:51.765 12143 12143 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:95)
05-29 02:22:51.765 12143 12143 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
05-29 02:22:51.765 12143 12143 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6186)
05-29 02:22:51.765 12143 12143 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
05-29 02:22:51.765 12143 12143 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
05-29 02:22:51.765 12143 12143 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
05-29 02:22:51.768  1901  7375 W ActivityManager:   Force finishing activity com.ubercab/.presidio.app.core.root.RootActivity
```
I'm running LineageOS 14.1 and latest microg 0.2.4-92, but I had same issue when I was on cm 13.

**Comment by alinefr** [comment] 2017-05-30 01:37
My issue seems to be the same as #340

**Comment by ksala** [comment] 2017-05-30 02:46
I just took an Uber on my phone with Microg, this is my experience:
* last version to date launch, but crashes after some seconds
* Version 3.147.7 launch, but crashes after some seconds (same behavior of the last version)
* Version 3.143.2 worked fine-ish (enough to get me where I wanted).

I kinda of wonder if this is related to push notifications - I didn't allow access to them to the two later versions, but allowed it on 3.143.2.

**Comment by okias** [comment] 2017-06-04 20:59
@ksala thank you for working build (3.143.2, in Yalp store it's number 33704 ).

@alinefr @mar-v-in thank you for making & pushing fix, excited to test it soon :)

**Comment by ale5000-git** [comment] 2017-06-13 07:15
@8bitjoe @alinefr @okias
Have you tried the new version?

**Comment by okias** [comment] 2017-06-16 17:36
Fixed in latest build.

**Comment by ksala** [comment] 2017-06-19 08:54
Excuse for my late reply, I can confirm that I was able to book an Uber with the latest version of the App + the latest version of MicroG.

The App had other issues (street names "blinking" black and after a while it just went all black), but I don't think this discussion is for this ticket.  
Sadly I won't get to try it again as I'm not an usual Uber user, just used it twice in a trip in NYC.

**Closed** 2017-06-19 09:30 UTC
